In [1]:
import numpy as np
import pandas as pd
import csv_figures
from csv_figures import add_time_col
from csv_figures import annual_Norm
import matplotlib.pyplot as plt
import requests
from matplotlib.widgets import CheckButtons

In [2]:
DBoccia = pd.read_excel('../../Cleaned_data/AnchorageSolar_cleaned/16DBoccia_cleaned.xlsx')
LWaller = pd.read_excel('../../Cleaned_data/AnchorageSolar_cleaned/16LWaller_cleaned.xlsx')
MAngstman = pd.read_excel('../../Cleaned_data/AnchorageSolar_cleaned/16Mangstman_cleaned.xlsx')
May = pd.read_excel('../../Cleaned_data/AnchorageSolar_cleaned/16May_cleaned.xlsx')
Pcrofut = pd.read_excel('../../Cleaned_data/AnchorageSolar_cleaned/16Pcrofut_cleaned.xlsx')
SDowns = pd.read_excel('../../Cleaned_data/AnchorageSolar_cleaned/16SDowns_cleaned.xlsx')

In [3]:
DBoccia_new = add_time_col(DBoccia)
LWaller_new = add_time_col(LWaller)
MAngstman_new = add_time_col(MAngstman)
May_new = add_time_col(May)
Pcrofut_new = add_time_col(Pcrofut)
SDowns_new = add_time_col(SDowns)

/Users/guge/Desktop/acep-solar/new/ACEP_solar/GEGU/figures/csv_figures.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  dataframe['Date'][i] = str(dataframe['Year'][i]) + '-' + str(dataframe['Month'][i])

In [4]:
D_annual_values,D_month = annual_Norm(DBoccia_new)
L_annual_values,L_month = annual_Norm(LWaller_new)
MA_annual_values,MA_month = annual_Norm(MAngstman_new)
May_annual_values,May_month = annual_Norm(May_new)
P_annual_values,P_month = annual_Norm(Pcrofut_new)
S_annual_values,S_month = annual_Norm(SDowns_new)

In [5]:
new_D = pd.DataFrame({'Date':D_month,'DBoccia':D_annual_values})
new_L = pd.DataFrame({'Date':L_month,'LWaller':L_annual_values})
new_MA = pd.DataFrame({'Date':MA_month,'MAngstman':MA_annual_values})
new_May = pd.DataFrame({'Date':May_month,'May':May_annual_values})
new_P = pd.DataFrame({'Date':P_month,'Pcrofut':P_annual_values})
new_S = pd.DataFrame({'Date':S_month,'SDowns':S_annual_values})
result = pd.merge(new_D,new_L,on='Date',how='outer')
result = pd.merge(result,new_MA,on='Date',how='outer')
result = pd.merge(result,new_May,on='Date',how='outer')
result = pd.merge(result,new_P,on='Date',how='outer')
Anchorage_16= pd.merge(result,new_S,on='Date',how='outer')
# #Anchorage_16 = result.fillna("")
Anchorage_16['Mean'] = Anchorage_16.mean(axis=1)
Anchorage_16 = Anchorage_16.sort_values(by = ['Date'])
Anchorage_16

Empty DataFrame
Columns: [DBoccia, LWaller, MAngstman, May, Pcrofut, Date, SDowns, Mean]
Index: []

In [6]:
# Get the data from the PV Watts --TMY2
list_parameters = {"formt": 'JSON', "api_key": "spJFj2l5ghY5jwk7dNfVYs3JHbpR6BOGHQNO8Y9Z", "system_capacity": 14, "module_type": 0, "losses": 14.08,
              "array_type": 0, "tilt": 50, "azimuth": 180, "lat": 61.21, "lon": -149.89, "dataset": 'tmy2'}
json_response = requests.get("https://developer.nrel.gov/api/pvwatts/v6", params = list_parameters).json()
TMY2 = pd.DataFrame(data = json_response['outputs'])
# Get the data from the PV Watts --TMY2
list_parameters = {"formt": 'JSON', "api_key": "spJFj2l5ghY5jwk7dNfVYs3JHbpR6BOGHQNO8Y9Z", "system_capacity": 14, "module_type": 0, "losses": 14.08,
              "array_type": 0, "tilt": 50, "azimuth": 180, "lat": 61.20, "lon": -149.73, "dataset": 'tmy3'}
json_response = requests.get("https://developer.nrel.gov/api/pvwatts/v6", params = list_parameters).json()
TMY3 = pd.DataFrame(data = json_response['outputs'])

In [7]:
Anchorage_16['TMY2'] = TMY2['ac_monthly']
Anchorage_16['TMY3'] = TMY3['ac_monthly']

In [8]:
#Anchorage_16.drop(['TMY2_annual','TMY3_annual'],axis = 1,inplace = True)
TMY2_low = TMY2['ac_annual'][2]*0.95/14
TMY2_high = TMY2['ac_annual'][2]*1.05/14

TMY3_low = TMY3['ac_annual'][2]*0.95/14
TMY3_high = TMY3['ac_annual'][2]*1.05/14

In [9]:
Anchorage_16['TMY2_low'] = TMY2_low
Anchorage_16['TMY2_high'] = TMY2_high
Anchorage_16['TMY3_low'] = TMY3_low
Anchorage_16['TMY3_high'] = TMY3_high

In [10]:
Anchorage_16

,DBoccia,LWaller,MAngstman,May,Pcrofut,Date,SDowns,Mean,TMY2,TMY3,TMY2_low,TMY2_high,TMY3_low,TMY3_high
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,300.178833,216.280655,877.099958,969.42627,900.563487,995.359644
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,691.071716,410.580841,877.099958,969.42627,900.563487,995.359644
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1330.001953,1217.677368,877.099958,969.42627,900.563487,995.359644
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1533.541016,1707.770386,877.099958,969.42627,900.563487,995.359644
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1842.311279,1908.405029,877.099958,969.42627,900.563487,995.359644
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1707.377441,2087.946533,877.099958,969.42627,900.563487,995.359644
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1655.989868,1642.537109,877.099958,969.42627,900.563487,995.359644
7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1366.767334,1499.759521,877.099958,969.42627,900.563487,995.359644
8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1137.300537,1290.349365,877.099958,969.42627,900.563487,995.359644
9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,671.748047,827.890869,877.099958,969.42627,900.563487,995.359644
10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,476.994904,306.113281,877.099958,969.42627,900.563487,995.359644
11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,212.398697,156.149460,877.099958,969.42627,900.563487,995.359644

In [11]:
# So now, let's try to draw a plot with checkbox
%matplotlib qt5
fig, ax = plt.subplots(figsize = (15, 8))
x = Anchorage_16['Date']


y_D = Anchorage_16['DBoccia']
l0, = ax.plot(x ,y_D,label='DBoccia')

y_L = Anchorage_16['LWaller']
l1, = ax.plot(x ,y_L,label='LWaller')


y_M = Anchorage_16['MAngstman']
l2, = ax.plot(x ,y_M)


y_May = Anchorage_16['May']
l3, = ax.plot(x ,y_May)

y_P = Anchorage_16['Pcrofut']
l4, = ax.plot(x,y_P,label='Pcrofut')


#y_S = Anchorage_16['SDowns']
#l5, = ax.plot(x,y_S,label = 'SDowns(BP)')

y_mean = Anchorage_16['Mean']
l6, = ax.plot(x,y_mean,label='Mean')

#y_TMY2 = Anchorage_16['TMY2']
#l7, = ax.plot(x,y_TMY2,'--',label = 'TMY2_ac_monthly')

#y_TMY3 = Anchorage_16['TMY3']
#l8, = ax.plot(x,y_TMY3,'--',label = 'TMY3_ac_monthly')

y_TMY2_low = Anchorage_16['TMY2_low']
l9, = ax.plot(x,y_TMY2_low,'--',label = 'TMY2_low')

y_TMY2_high = Anchorage_16['TMY2_high']
l10, = ax.plot(x,y_TMY2_high,'--',label = 'TMY2_high')

y_TMY3_low = Anchorage_16['TMY3_low']
l11, = ax.plot(x,y_TMY3_low,'-.',label = 'TMY3_low')

y_TMY3_high = Anchorage_16['TMY3_high']
l12, = ax.plot(x,y_TMY3_high,'-.',label = 'TMY3_high')

# # #ax.plot(x=range(len(result['Date'][49:90])),y = result['Mean'][49:90],label='Average')
# # #ax.plot(x=range(len(result['Date'][49:90])),y = result['TMY2_low'][49:90],label='TMY2_low') 
# #ax.plot(x=range(len(result['Date'][49:90])),y = result['TMY2_high'][49:90],label ='TMY2_high')

#this is where we can adjust the subplots side/top/buttom width
# tick_spacing = np.linspace(1, len(Anchorage_16.index)-1,12, dtype = 'int')
# Date_shown = []
# for i in tick_spacing:
#     Date_shown.append(Anchorage_16['Date'][i])
#ax.xticks(tick_spacing,Date_shown)
#plt.annotate('THY2_high',xy=(30,1072.991757),xytext=(32,1100),arrowprops=dict(facecolor='black', shrink=0.05))
#plt.annotate('THY2_low',xy=(10,970.802066),xytext=(6,930),arrowprops=dict(facecolor='black', shrink=0.05))
# ax.set_xticks(tick_spacing)
ax.set_title("Rolling 12-Month Average of Produced Power, Over Time", size = 18)
ax.set_xlabel("Month", size = 14)
ax.set_ylabel("AC Power Produced (kWh) per DC Power Installed (kW)", size = 14)
ax.legend()


plt.subplots_adjust(left=0.2)
lines = [l0, l1, l2, l3, l4, l6,l9, l10, l11, l12]

# Make checkbuttons with all plotted lines with correct visibility
rax = plt.axes([0.005, 0.5, 0.15, 0.4])
labels = [str(line.get_label()) for line in lines]
visibility = [line.get_visible() for line in lines]
check = CheckButtons(rax, labels, visibility)


def func(label):
    index = labels.index(label)
    lines[index].set_visible(not lines[index].get_visible())
    plt.draw()

check.on_clicked(func)


# Some 

plt.show()

#Ok,this seems to be fine,maybe we will talk about it after.