In [1]:
import numpy as np
import pandas as pd
import csv_figures
from csv_figures import add_time_col
from csv_figures import annual_Norm
import matplotlib.pyplot as plt
import requests
from matplotlib.widgets import CheckButtons

In [2]:
nenana = pd.read_excel('../../Cleaned_data/RuralAk/RuralAK_Nenana_cleaned.xlsx')

In [3]:
nenana_new = add_time_col(nenana)

/Users/guge/Desktop/acep-solar/new/ACEP_solar/GEGU/figures/csv_figures.py:26: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  dataframe['Date'][i] = str(dataframe['Year'][i]) + '-' + str(dataframe['Month'][i])

In [4]:
nenana_annual_values,nenana_month = annual_Norm(nenana_new)

In [5]:
new_nenana = pd.DataFrame({'Date':nenana_month,'nenana':nenana_annual_values})

In [6]:
# Get the data from the PV Watts --TMY2
list_parameters = {"formt": 'JSON', "api_key": "spJFj2l5ghY5jwk7dNfVYs3JHbpR6BOGHQNO8Y9Z", "system_capacity": 4.4, "module_type": 0, "losses": 14.08,
              "array_type": 0, "tilt": 50, "azimuth": 180, "lat": 64.56, "lon": -149.03, "dataset": 'tmy2'}
json_response = requests.get("https://developer.nrel.gov/api/pvwatts/v6", params = list_parameters).json()
TMY2 = pd.DataFrame(data = json_response['outputs'])
# Get the data from the PV Watts --TMY2
list_parameters = {"formt": 'JSON', "api_key": "spJFj2l5ghY5jwk7dNfVYs3JHbpR6BOGHQNO8Y9Z", "system_capacity": 4.4, "module_type": 0, "losses": 14.08,
              "array_type": 0, "tilt": 50, "azimuth": 180, "lat": 64.56, "lon": -149.03, "dataset": 'tmy3'}
json_response = requests.get("https://developer.nrel.gov/api/pvwatts/v6", params = list_parameters).json()
TMY3 = pd.DataFrame(data = json_response['outputs'])

In [7]:
TMY2_low = TMY2['ac_annual'][2]*0.95/4.4
TMY2_high = TMY2['ac_annual'][2]*1.05/4.4

TMY3_low = TMY3['ac_annual'][2]*0.95/4.4
TMY3_high = TMY3['ac_annual'][2]*1.05/4.4

new_nenana['TMY2_low'] = TMY2_low
new_nenana['TMY2_high'] = TMY2_high
new_nenana['TMY3_low'] = TMY3_low
new_nenana['TMY3_high'] = TMY3_high
new_nenana

         Date       nenana    TMY2_low    TMY2_high    TMY3_low   TMY3_high
0  2012-01-01  1089.194318  970.802124  1072.991821  977.569208  1080.47123
1  2012-02-01  1095.051818  970.802124  1072.991821  977.569208  1080.47123
2  2012-03-01  1093.367500  970.802124  1072.991821  977.569208  1080.47123
3  2012-04-01  1032.012727  970.802124  1072.991821  977.569208  1080.47123
4  2012-05-01  1035.561364  970.802124  1072.991821  977.569208  1080.47123
5  2012-06-01  1015.326591  970.802124  1072.991821  977.569208  1080.47123
6  2012-07-01  1015.327045  970.802124  1072.991821  977.569208  1080.47123
7  2012-08-01  1014.369091  970.802124  1072.991821  977.569208  1080.47123
8  2012-09-01  1010.930000  970.802124  1072.991821  977.569208  1080.47123
9  2012-10-01   990.063864  970.802124  1072.991821  977.569208  1080.47123
10 2012-11-01   999.123636  970.802124  1072.991821  977.569208  1080.47123
11 2012-12-01  1007.190455  970.802124  1072.991821  977.569208  1080.47123
12 2013-01-01  1007.869545  970.802124  1072.991821  977.569208  1080.47123
13 2013-02-01  1007.431818  970.802124  1072.991821  977.569208  1080.47123
14 2013-03-01  1000.259318  970.802124  1072.991821  977.569208  1080.47123
15 2013-04-01  1017.486364  970.802124  1072.991821  977.569208  1080.47123
16 2013-05-01  1022.121364  970.802124  1072.991821  977.569208  1080.47123
17 2013-06-01  1060.420455  970.802124  1072.991821  977.569208  1080.47123
18 2013-07-01  1082.698864  970.802124  1072.991821  977.569208  1080.47123
19 2013-08-01  1086.332273  970.802124  1072.991821  977.569208  1080.47123
20 2013-09-01  1096.152727  970.802124  1072.991821  977.569208  1080.47123
21 2013-10-01  1086.035455  970.802124  1072.991821  977.569208  1080.47123
22 2013-11-01  1062.008636  970.802124  1072.991821  977.569208  1080.47123
23 2013-12-01  1052.864091  970.802124  1072.991821  977.569208  1080.47123
24 2014-01-01  1052.431136  970.802124  1072.991821  977.569208  1080.47123
25 2014-02-01  1054.210909  970.802124  1072.991821  977.569208  1080.47123
26 2014-03-01  1085.197045  970.802124  1072.991821  977.569208  1080.47123
27 2014-04-01  1117.277273  970.802124  1072.991821  977.569208  1080.47123
28 2014-05-01  1108.552045  970.802124  1072.991821  977.569208  1080.47123
29 2014-06-01  1066.407500  970.802124  1072.991821  977.569208  1080.47123
..        ...          ...         ...          ...         ...         ...
54 2016-07-01   775.531136  970.802124  1072.991821  977.569208  1080.47123
55 2016-08-01   838.312727  970.802124  1072.991821  977.569208  1080.47123
56 2016-09-01   877.330227  970.802124  1072.991821  977.569208  1080.47123
57 2016-10-01   874.284545  970.802124  1072.991821  977.569208  1080.47123
58 2016-11-01   891.024318  970.802124  1072.991821  977.569208  1080.47123
59 2016-12-01   888.102045  970.802124  1072.991821  977.569208  1080.47123
60 2017-01-01   887.931818  970.802124  1072.991821  977.569208  1080.47123
61 2017-02-01   887.931818  970.802124  1072.991821  977.569208  1080.47123
62 2017-03-01   888.045455  970.802124  1072.991821  977.569208  1080.47123
63 2017-04-01   885.681818  970.802124  1072.991821  977.569208  1080.47123
64 2017-05-01   944.545455  970.802124  1072.991821  977.569208  1080.47123
65 2017-06-01   961.818182  970.802124  1072.991821  977.569208  1080.47123
66 2017-07-01   952.272727  970.802124  1072.991821  977.569208  1080.47123
67 2017-08-01   926.590909  970.802124  1072.991821  977.569208  1080.47123
68 2017-09-01   874.545455  970.802124  1072.991821  977.569208  1080.47123
69 2017-10-01   876.818182  970.802124  1072.991821  977.569208  1080.47123
70 2017-11-01   836.818182  970.802124  1072.991821  977.569208  1080.47123
71 2017-12-01   834.659091  970.802124  1072.991821  977.569208  1080.47123
72 2018-01-01   834.659091  970.802124  1072.991821  977.569208  1080.47123
73 2018-02-01   834.659091  970.802124  1072.991821  977.569208  1080.47123
74 2018-03-01   834.431818  970.802124  1072.991821  977.569208  1080.47123
75 2018-04-01   830.636364  970.802124  1072.991821  977.569208  1080.47123
76 2018-05-01   700.181818  970.802124  1072.991821  977.569208  1080.47123
77 2018-06-01   721.772727  970.802124  1072.991821  977.569208  1080.47123
78 2018-07-01   709.500000  970.802124  1072.991821  977.569208  1080.47123
79 2018-08-01   711.318182  970.802124  1072.991821  977.569208  1080.47123
80 2018-09-01   749.954545  970.802124  1072.991821  977.569208  1080.47123
81 2018-10-01   780.181818  970.802124  1072.991821  977.569208  1080.47123
82 2018-11-01   800.863636  970.802124  1072.991821  977.569208  1080.47123
83 2018-12-01   800.977273  970.802124  1072.991821  977.569208  1080.47123

[84 rows x 6 columns]

In [9]:
%matplotlib qt5
fig, ax = plt.subplots(figsize = (15, 8))
x = new_nenana['Date']


y_fort = new_nenana['nenana']
l0, = ax.plot(x ,y_fort,label='Nenana')

y_TMY2_low = new_nenana['TMY2_low']
l1, = ax.plot(x,y_TMY2_low,'-.',label = 'TMY2_low')

y_TMY2_high = new_nenana['TMY2_high']
l2, = ax.plot(x,y_TMY2_high,'-.',label = 'TMY2_high')

y_TMY3_low = new_nenana['TMY3_low']
l3, = ax.plot(x,y_TMY3_low,'-.',label = 'TMY3_low')

y_TMY3_high = new_nenana['TMY3_high']
l4, = ax.plot(x,y_TMY3_high,'-.',label = 'TMY3_high')

ax.set_title("Rolling 12-Month Average of Produced Power, Over Time", size = 18)
ax.set_xlabel("Month", size = 14)
ax.set_ylabel("AC Power Produced (kWh) per DC Power Installed (kW)", size = 14)
ax.legend()


plt.subplots_adjust(left=0.2)
lines = [l0, l1, l2, l3, l4]

# Make checkbuttons with all plotted lines with correct visibility
rax = plt.axes([0.005, 0.48, 0.15, 0.4])
labels = [str(line.get_label()) for line in lines]
visibility = [line.get_visible() for line in lines]
check = CheckButtons(rax, labels, visibility)


def func(label):
    index = labels.index(label)
    lines[index].set_visible(not lines[index].get_visible())
    plt.draw()

check.on_clicked(func)


# Some 

plt.show()

#Ok,this seems to be fine,maybe we will talk about it after.