In [2]:
import pandas as pd
import numpy as np
from the_needed_function import drop_the_hours
from the_needed_function import seperate_date

In [5]:
braun_fairbanks = pd.read_csv('../Cleaned_data/ABS Alaskan/braun/572156_system_energy_20150226_to_20190522.csv')
Dashevsky_fairbanks = pd.read_csv('../Cleaned_data/ABS Alaskan/Dashevsky/721120_system_energy_20150828_to_20190522 (1).csv')
davis_Wasilla = pd.read_csv('../Cleaned_data/ABS Alaskan/Davis/273944_system_energy_20131115_to_20190522.csv')
deer_fairbanks = pd.read_csv('../Cleaned_data/ABS Alaskan/Deer/1062205_system_energy_20160927_to_20190522.csv')
dukeminier_fairbanks = pd.read_csv('../Cleaned_data/ABS Alaskan/Dukeminier/716566_system_energy_20150824_to_20190522.csv')
fireweed_Anchorage = pd.read_csv('../Cleaned_data/ABS Alaskan/FireweedBusCenter/945883_system_energy_20160520_to_20190522.csv')
Tran_fairbanks = pd.read_csv('../Cleaned_data/ABS Alaskan/GenaTran/28253_system_energy_20110826_to_20190522.csv')
grubis_fairbanks = pd.read_csv('../Cleaned_data/ABS Alaskan/Grubis/660658_system_energy_20150705_to_20190522.csv')
hall_North_pole = pd.read_csv('../Cleaned_data/ABS Alaskan/Hall/1000407_system_energy_20160804_to_20190522.csv')
jorgenson_fairbanks = pd.read_csv('../Cleaned_data/ABS Alaskan/jorgenson/802562_system_energy_20151221_to_20190522.csv')
kogl_denali_park = pd.read_csv('../Cleaned_data/ABS Alaskan/Kogl/1030153_system_energy_20160929_to_20190522.csv')
ronlevy_Soldotna = pd.read_csv('../Cleaned_data/ABS Alaskan/RonLevy/29009_system_energy_20110831_to_20190522.csv')
albin_fairbanks = pd.read_csv('../Cleaned_data/ABS Alaskan/SolarFox/394826_system_energy_20140729_to_20190522.csv')
wiessman_fairbanks = pd.read_csv('../Cleaned_data/ABS Alaskan/Wiessman_Fairbanks/720232_system_energy_20150827_to_20190522.csv')

In [6]:
drop_the_hours(braun_fairbanks)
drop_the_hours(Dashevsky_fairbanks)
drop_the_hours(davis_Wasilla)
drop_the_hours(deer_fairbanks)
drop_the_hours(dukeminier_fairbanks)
drop_the_hours(fireweed_Anchorage)
drop_the_hours(Tran_fairbanks)
drop_the_hours(grubis_fairbanks)
drop_the_hours(hall_North_pole)
drop_the_hours(jorgenson_fairbanks)
drop_the_hours(kogl_denali_park)
drop_the_hours(ronlevy_Soldotna)
drop_the_hours(albin_fairbanks)
drop_the_hours(wiessman_fairbanks)

      Date/Time  Energy Produced (Wh)
0     8/27/2015                  2927
1     8/28/2015                  7106
2     8/29/2015                  6720
3     8/30/2015                 12858
4     8/31/2015                 11036
5      9/1/2015                 17431
6      9/2/2015                 19792
7      9/3/2015                 16644
8      9/4/2015                 16377
9      9/5/2015                 18488
10     9/6/2015                 20350
11     9/7/2015                 14510
12     9/8/2015                  8682
13     9/9/2015                  8949
14    9/10/2015                  8961
15    9/11/2015                 13280
16    9/12/2015                  4609
17    9/13/2015                  1953
18    9/14/2015                  3047
19    9/15/2015                  4078
20    9/16/2015                  3011
21    9/17/2015                  3016
22    9/18/2015                  3909
23    9/19/2015                  3541
24    9/20/2015                  4014
25    9/21/2015                  4243
26    9/22/2015                  8517
27    9/23/2015                  5417
28    9/24/2015                 17821
29    9/25/2015                   596
...         ...                   ...
1335  4/23/2019                  3508
1336  4/24/2019                 17846
1337  4/25/2019                 21460
1338  4/26/2019                 21563
1339  4/27/2019                 21442
1340  4/28/2019                 21607
1341  4/29/2019                 21576
1342  4/30/2019                 20984
1343   5/1/2019                 20817
1344   5/2/2019                 12399
1345   5/3/2019                 11736
1346   5/4/2019                 14538
1347   5/5/2019                 20888
1348   5/6/2019                 11974
1349   5/7/2019                 17452
1350   5/8/2019                  5904
1351   5/9/2019                 21282
1352  5/10/2019                 10988
1353  5/11/2019                 13557
1354  5/12/2019                 19729
1355  5/13/2019                 14954
1356  5/14/2019                 13586
1357  5/15/2019                 21436
1358  5/16/2019                 22427
1359  5/17/2019                 22201
1360  5/18/2019                 14843
1361  5/19/2019                 19879
1362  5/20/2019                 17119
1363  5/21/2019                 20463
1364  5/22/2019                 17326

[1365 rows x 2 columns]

In [7]:
braun_fairbanks_new = seperate_date(braun_fairbanks)
Dashevsky_fairbanks_new = seperate_date(Dashevsky_fairbanks)
davis_Wasilla_new = seperate_date(davis_Wasilla)
deer_fairbanks_new = seperate_date(deer_fairbanks)
dukeminier_fairbanks_new = seperate_date(dukeminier_fairbanks)
fireweed_Anchorage_new = seperate_date(fireweed_Anchorage)
Tran_fairbanks_new = seperate_date(Tran_fairbanks)
grubis_fairbanks_new = seperate_date(grubis_fairbanks)
hall_North_pole_new = seperate_date(hall_North_pole)
jorgenson_fairbanks_new = seperate_date(jorgenson_fairbanks)
kogl_denali_park_new = seperate_date(kogl_denali_park)
ronlevy_Soldotna_new = seperate_date(ronlevy_Soldotna)
albin_fairbanks_new = seperate_date(albin_fairbanks)
wiessman_fairbanks_new = seperate_date(wiessman_fairbanks)

In [9]:
braun_fairbanks_new['Interpolate']=0
braun_fairbanks_new['DC Capacity']= ""
braun_fairbanks_new['Location']= ""
braun_fairbanks_new['DC Capacity'][0]=3.75
braun_fairbanks_new['Location'][0]='Fairbanks'

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [11]:
braun_fairbanks_new.to_csv('braun_fairbanks_new',index=False)

In [12]:
Dashevsky_fairbanks_new['Interpolate']=0
Dashevsky_fairbanks_new['DC Capacity']= ""
Dashevsky_fairbanks_new['Location']= ""
Dashevsky_fairbanks_new['DC Capacity'][0]=3.06
Dashevsky_fairbanks_new['Location'][0]='Fairbanks'
Dashevsky_fairbanks_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

      Year  Month  Day  Energy  Interpolate DC Capacity   Location
0     2015      8   28   1.108            0        3.06  Fairbanks
1     2015      8   29   2.616            0
2     2015      8   30   5.588            0
3     2015      8   31   4.681            0
4     2015      9    1   8.323            0
5     2015      9    2   8.393            0
6     2015      9    3   8.436            0
7     2015      9    4   8.153            0
8     2015      9    5   8.204            0
9     2015      9    6   8.054            0
10    2015      9    7   8.018            0
11    2015      9    8   5.169            0
12    2015      9    9   5.496            0
13    2015      9   10   3.452            0
14    2015      9   11   6.387            0
15    2015      9   12   2.476            0
16    2015      9   13   0.821            0
17    2015      9   14   1.330            0
18    2015      9   15   1.985            0
19    2015      9   16   1.371            0
20    2015      9   17   1.378            0
21    2015      9   18   2.661            0
22    2015      9   19   1.310            0
23    2015      9   20   3.173            0
24    2015      9   21   2.987            0
25    2015      9   22   7.227            0
26    2015      9   23   2.977            0
27    2015      9   24   8.310            0
28    2015      9   25   0.688            0
29    2015      9   26   2.938            0
...    ...    ...  ...     ...          ...         ...        ...
1334  2019      4   23   0.000            0
1335  2019      4   24   0.000            0
1336  2019      4   25   0.000            0
1337  2019      4   26   0.000            0
1338  2019      4   27   0.000            0
1339  2019      4   28   0.000            0
1340  2019      4   29   0.000            0
1341  2019      4   30   0.000            0
1342  2019      5    1   0.000            0
1343  2019      5    2   0.000            0
1344  2019      5    3   0.000            0
1345  2019      5    4   0.000            0
1346  2019      5    5   0.000            0
1347  2019      5    6   0.000            0
1348  2019      5    7   0.000            0
1349  2019      5    8   0.000            0
1350  2019      5    9   0.000            0
1351  2019      5   10   0.000            0
1352  2019      5   11   0.000            0
1353  2019      5   12   0.000            0
1354  2019      5   13   0.000            0
1355  2019      5   14   0.000            0
1356  2019      5   15   0.000            0
1357  2019      5   16   0.000            0
1358  2019      5   17   0.000            0
1359  2019      5   18   0.000            0
1360  2019      5   19   0.000            0
1361  2019      5   20   0.000            0
1362  2019      5   21   0.000            0
1363  2019      5   22   0.000            0

[1364 rows x 7 columns]

In [13]:
Dashevsky_fairbanks_new.to_csv('Dashevsky_fairbanks_new',index=False)

In [14]:
davis_Wasilla_new['Interpolate']=0
davis_Wasilla_new['DC Capacity']= ""
davis_Wasilla_new['Location']= ""
davis_Wasilla_new['DC Capacity'][0]=1.5
davis_Wasilla_new['Location'][0]='Wasilla'
davis_Wasilla_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

      Year  Month  Day  Energy  Interpolate DC Capacity Location
0     2013     11   15   0.003            0         1.5  Wasilla
1     2013     11   16   0.034            0
2     2013     11   17   0.038            0
3     2013     11   18   0.044            0
4     2013     11   19   0.042            0
5     2013     11   20   0.042            0
6     2013     11   21   0.044            0
7     2013     11   22   0.039            0
8     2013     11   23   0.000            0
9     2013     11   24   0.002            0
10    2013     11   25   0.002            0
11    2013     11   26   0.026            0
12    2013     11   27   0.000            0
13    2013     11   28   0.000            0
14    2013     11   29   0.012            0
15    2013     11   30   0.038            0
16    2013     12    1   0.040            0
17    2013     12    2   0.060            0
18    2013     12    3   0.064            0
19    2013     12    4   0.032            0
20    2013     12    5   0.021            0
21    2013     12    6   0.021            0
22    2013     12    7   0.024            0
23    2013     12    8   0.009            0
24    2013     12    9   0.014            0
25    2013     12   10   0.002            0
26    2013     12   11   0.026            0
27    2013     12   12   0.018            0
28    2013     12   13   0.012            0
29    2013     12   14   0.000            0
...    ...    ...  ...     ...          ...         ...      ...
1985  2019      4   23   0.000            0
1986  2019      4   24   0.000            0
1987  2019      4   25   0.000            0
1988  2019      4   26   0.000            0
1989  2019      4   27   0.000            0
1990  2019      4   28   0.000            0
1991  2019      4   29   0.000            0
1992  2019      4   30   0.000            0
1993  2019      5    1   0.000            0
1994  2019      5    2   0.000            0
1995  2019      5    3   0.000            0
1996  2019      5    4   0.000            0
1997  2019      5    5   0.000            0
1998  2019      5    6   0.000            0
1999  2019      5    7   0.000            0
2000  2019      5    8   0.000            0
2001  2019      5    9   0.000            0
2002  2019      5   10   0.000            0
2003  2019      5   11   0.000            0
2004  2019      5   12   0.000            0
2005  2019      5   13   0.000            0
2006  2019      5   14   0.000            0
2007  2019      5   15   0.000            0
2008  2019      5   16   0.000            0
2009  2019      5   17   0.000            0
2010  2019      5   18   0.000            0
2011  2019      5   19   0.000            0
2012  2019      5   20   0.000            0
2013  2019      5   21   0.000            0
2014  2019      5   22   0.000            0

[2015 rows x 7 columns]

In [15]:
davis_Wasilla_new.to_csv('davis_Wasilla_new',index=False)

In [16]:
deer_fairbanks_new['Interpolate']=0
deer_fairbanks_new['DC Capacity']= ""
deer_fairbanks_new['Location']= ""
deer_fairbanks_new['DC Capacity'][0]=3.5
deer_fairbanks_new['Location'][0]='Fairbanks'
deer_fairbanks_new.to_csv('deer_fairbanks_new',index=False)

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [18]:
dukeminier_fairbanks_new['Interpolate']=0
dukeminier_fairbanks_new['DC Capacity']= ""
dukeminier_fairbanks_new['Location']= ""
dukeminier_fairbanks_new['DC Capacity'][0]=4.08
dukeminier_fairbanks_new['Location'][0]='Fairbanks'
dukeminier_fairbanks_new.to_csv('dukeminier_fairbanks_new',index=False)

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [20]:
fireweed_Anchorage_new['Interpolate']=0
fireweed_Anchorage_new['DC Capacity']= ""
fireweed_Anchorage_new['Location']= ""
fireweed_Anchorage_new['DC Capacity'][0]=11.9
fireweed_Anchorage_new['Location'][0]='Anchorage'
fireweed_Anchorage_new.to_csv('fireweed_Anchorage_new',index=False)
fireweed_Anchorage_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

      Year  Month  Day  Energy  Interpolate DC Capacity   Location
0     2016      5   20   0.000            0        11.9  Anchorage
1     2016      5   21   0.000            0
2     2016      5   22   0.000            0
3     2016      5   23   0.000            0
4     2016      5   24   0.000            0
5     2016      5   25   0.000            0
6     2016      5   26   0.000            0
7     2016      5   27   0.000            0
8     2016      5   28   0.000            0
9     2016      5   29   0.000            0
10    2016      5   30   0.000            0
11    2016      5   31   0.000            0
12    2016      6    1   0.000            0
13    2016      6    2   1.188            0
14    2016      6    3  34.968            0
15    2016      6    4  19.554            0
16    2016      6    5  48.663            0
17    2016      6    6   7.954            0
18    2016      6    7  52.327            0
19    2016      6    8  64.818            0
20    2016      6    9  64.666            0
21    2016      6   10  34.485            0
22    2016      6   11  33.723            0
23    2016      6   12  32.945            0
24    2016      6   13  58.609            0
25    2016      6   14  63.020            0
26    2016      6   15  64.036            0
27    2016      6   16  62.805            0
28    2016      6   17  62.305            0
29    2016      6   18  51.575            0
...    ...    ...  ...     ...          ...         ...        ...
1068  2019      4   23  53.954            0
1069  2019      4   24  61.717            0
1070  2019      4   25  62.494            0
1071  2019      4   26  85.701            0
1072  2019      4   27  84.972            0
1073  2019      4   28  86.210            0
1074  2019      4   29  37.071            0
1075  2019      4   30  78.391            0
1076  2019      5    1  65.506            0
1077  2019      5    2  27.012            0
1078  2019      5    3  61.649            0
1079  2019      5    4  47.905            0
1080  2019      5    5  24.976            0
1081  2019      5    6  37.857            0
1082  2019      5    7  55.885            0
1083  2019      5    8  50.823            0
1084  2019      5    9  38.175            0
1085  2019      5   10  33.610            0
1086  2019      5   11  49.151            0
1087  2019      5   12  39.852            0
1088  2019      5   13  42.858            0
1089  2019      5   14  67.013            0
1090  2019      5   15  36.865            0
1091  2019      5   16  34.704            0
1092  2019      5   17  43.236            0
1093  2019      5   18  40.252            0
1094  2019      5   19  47.685            0
1095  2019      5   20  35.761            0
1096  2019      5   21  85.948            0
1097  2019      5   22  64.229            0

[1098 rows x 7 columns]

In [21]:
Tran_fairbanks_new['Interpolate']=0
Tran_fairbanks_new['DC Capacity']= ""
Tran_fairbanks_new['Location']= ""
Tran_fairbanks_new['DC Capacity'][0]=1.9
Tran_fairbanks_new['Location'][0]='Fairbanks'
Tran_fairbanks_new.to_csv('Tran_fairbanks_new',index=False)
Tran_fairbanks_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

      Year  Month  Day  Energy  Interpolate DC Capacity   Location
0     2011      8   26   6.584            0         1.9  Fairbanks
1     2011      8   27   8.018            0
2     2011      8   28   8.348            0
3     2011      8   29   7.610            0
4     2011      8   30   6.364            0
5     2011      8   31   4.081            0
6     2011      9    1   3.350            0
7     2011      9    2   4.603            0
8     2011      9    3   7.107            0
9     2011      9    4   7.228            0
10    2011      9    5   7.552            0
11    2011      9    6   3.447            0
12    2011      9    7   4.148            0
13    2011      9    8   3.557            0
14    2011      9    9   1.309            0
15    2011      9   10   0.837            0
16    2011      9   11   4.170            0
17    2011      9   12   5.562            0
18    2011      9   13   3.412            0
19    2011      9   14   2.388            0
20    2011      9   15   0.858            0
21    2011      9   16   5.303            0
22    2011      9   17   4.898            0
23    2011      9   18   6.406            0
24    2011      9   19   4.468            0
25    2011      9   20   2.845            0
26    2011      9   21   6.462            0
27    2011      9   22   1.565            0
28    2011      9   23   3.882            0
29    2011      9   24   1.136            0
...    ...    ...  ...     ...          ...         ...        ...
2797  2019      4   23   0.000            0
2798  2019      4   24   0.000            0
2799  2019      4   25   0.000            0
2800  2019      4   26   0.000            0
2801  2019      4   27   0.000            0
2802  2019      4   28   0.000            0
2803  2019      4   29   0.000            0
2804  2019      4   30   0.000            0
2805  2019      5    1   0.000            0
2806  2019      5    2   0.000            0
2807  2019      5    3   0.000            0
2808  2019      5    4   0.000            0
2809  2019      5    5   0.000            0
2810  2019      5    6   0.000            0
2811  2019      5    7   0.000            0
2812  2019      5    8   0.000            0
2813  2019      5    9   0.000            0
2814  2019      5   10   0.000            0
2815  2019      5   11   0.000            0
2816  2019      5   12   0.000            0
2817  2019      5   13   0.000            0
2818  2019      5   14   0.000            0
2819  2019      5   15   0.000            0
2820  2019      5   16   0.000            0
2821  2019      5   17   0.000            0
2822  2019      5   18   0.000            0
2823  2019      5   19   0.000            0
2824  2019      5   20   0.000            0
2825  2019      5   21   0.000            0
2826  2019      5   22   0.000            0

[2827 rows x 7 columns]

In [22]:
grubis_fairbanks_new['Interpolate']=0
grubis_fairbanks_new['DC Capacity']= ""
grubis_fairbanks_new['Location']= ""
grubis_fairbanks_new['DC Capacity'][0]=3.12
grubis_fairbanks_new['Location'][0]='Fairbanks'
grubis_fairbanks_new.to_csv('grubis_fairbanks_new',index=False)
grubis_fairbanks_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

      Year  Month  Day  Energy  Interpolate DC Capacity   Location
0     2015      7    5   0.010            0        3.12  Fairbanks
1     2015      7    6   6.139            0
2     2015      7    7   3.790            0
3     2015      7    8  12.401            0
4     2015      7    9   7.834            0
5     2015      7   10  20.255            0
6     2015      7   11  18.033            0
7     2015      7   12  12.314            0
8     2015      7   13  16.384            0
9     2015      7   14   3.319            0
10    2015      7   15  17.958            0
11    2015      7   16  20.688            0
12    2015      7   17  14.909            0
13    2015      7   18   4.149            0
14    2015      7   19   2.641            0
15    2015      7   20   6.554            0
16    2015      7   21  20.215            0
17    2015      7   22  20.659            0
18    2015      7   23  16.505            0
19    2015      7   24  12.554            0
20    2015      7   25  13.141            0
21    2015      7   26  13.733            0
22    2015      7   27   4.677            0
23    2015      7   28   9.009            0
24    2015      7   29  13.363            0
25    2015      7   30  10.520            0
26    2015      7   31  13.603            0
27    2015      8    1   6.332            0
28    2015      8    2   4.969            0
29    2015      8    3  14.965            0
...    ...    ...  ...     ...          ...         ...        ...
1388  2019      4   23   0.000            0
1389  2019      4   24   0.000            0
1390  2019      4   25   0.000            0
1391  2019      4   26   0.000            0
1392  2019      4   27   0.000            0
1393  2019      4   28   0.000            0
1394  2019      4   29   0.000            0
1395  2019      4   30   0.000            0
1396  2019      5    1   0.000            0
1397  2019      5    2   0.000            0
1398  2019      5    3   0.000            0
1399  2019      5    4   0.000            0
1400  2019      5    5   0.000            0
1401  2019      5    6   0.000            0
1402  2019      5    7   0.000            0
1403  2019      5    8   0.000            0
1404  2019      5    9   0.000            0
1405  2019      5   10   0.000            0
1406  2019      5   11   0.000            0
1407  2019      5   12   0.000            0
1408  2019      5   13   0.000            0
1409  2019      5   14   0.000            0
1410  2019      5   15   0.000            0
1411  2019      5   16   0.000            0
1412  2019      5   17   0.000            0
1413  2019      5   18   0.000            0
1414  2019      5   19   0.000            0
1415  2019      5   20   0.000            0
1416  2019      5   21   0.000            0
1417  2019      5   22   0.000            0

[1418 rows x 7 columns]

In [24]:
hall_North_pole_new['Interpolate']=0
hall_North_pole_new['DC Capacity']= ""
hall_North_pole_new['Location']= ""
hall_North_pole_new['DC Capacity'][0]=3.83
hall_North_pole_new['Location'][0]='North Pole'
hall_North_pole_new.to_csv('hall_North_pole_new',index=False)
hall_North_pole_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

      Year  Month  Day  Energy  Interpolate DC Capacity    Location
0     2016      8    4   0.000            0        3.83  North Pole
1     2016      8    5   0.000            0
2     2016      8    6   0.000            0
3     2016      8    7   0.000            0
4     2016      8    8  13.765            0
5     2016      8    9   7.877            0
6     2016      8   10  20.572            0
7     2016      8   11  15.916            0
8     2016      8   12   8.980            0
9     2016      8   13  21.274            0
10    2016      8   14  14.917            0
11    2016      8   15  15.923            0
12    2016      8   16  10.646            0
13    2016      8   17  18.646            0
14    2016      8   18  18.213            0
15    2016      8   19  10.784            0
16    2016      8   20   3.134            0
17    2016      8   21   5.235            0
18    2016      8   22  12.809            0
19    2016      8   23  13.403            0
20    2016      8   24   9.154            0
21    2016      8   25   3.134            0
22    2016      8   26  13.061            0
23    2016      8   27  13.774            0
24    2016      8   28  18.131            0
25    2016      8   29  18.172            0
26    2016      8   30  17.729            0
27    2016      8   31  15.392            0
28    2016      9    1  15.253            0
29    2016      9    2  17.072            0
...    ...    ...  ...     ...          ...         ...         ...
992   2019      4   23   4.338            0
993   2019      4   24  20.820            0
994   2019      4   25  24.363            0
995   2019      4   26  23.875            0
996   2019      4   27  23.702            0
997   2019      4   28  16.002            0
998   2019      4   29  31.271            0
999   2019      4   30  22.767            0
1000  2019      5    1  21.075            0
1001  2019      5    2  14.640            0
1002  2019      5    3  11.827            0
1003  2019      5    4  15.269            0
1004  2019      5    5  23.314            0
1005  2019      5    6  14.765            0
1006  2019      5    7  20.453            0
1007  2019      5    8   4.323            0
1008  2019      5    9  23.750            0
1009  2019      5   10   9.773            0
1010  2019      5   11  10.991            0
1011  2019      5   12  15.684            0
1012  2019      5   13  20.201            0
1013  2019      5   14  14.878            0
1014  2019      5   15  19.600            0
1015  2019      5   16  21.766            0
1016  2019      5   17  21.956            0
1017  2019      5   18  10.011            0
1018  2019      5   19  17.421            0
1019  2019      5   20  18.226            0
1020  2019      5   21  21.412            0
1021  2019      5   22  15.103            0

[1022 rows x 7 columns]

In [25]:
jorgenson_fairbanks_new['Interpolate']=0
jorgenson_fairbanks_new['DC Capacity']= ""
jorgenson_fairbanks_new['Location']= ""
jorgenson_fairbanks_new['DC Capacity'][0]=3.06
jorgenson_fairbanks_new['Location'][0]='Fairbanks'
jorgenson_fairbanks_new.to_csv('jorgenson_fairbanks_new',index=False)
jorgenson_fairbanks_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

      Year  Month  Day  Energy  Interpolate DC Capacity   Location
0     2015     12   21   0.064            0        3.06  Fairbanks
1     2015     12   22   0.917            0
2     2015     12   23   1.912            0
3     2015     12   24   2.577            0
4     2015     12   25   3.347            0
5     2015     12   26   4.066            0
6     2015     12   27   4.143            0
7     2015     12   28   4.143            0
8     2015     12   29   4.143            0
9     2015     12   30   4.143            0
10    2015     12   31   4.192            0
11    2016      1    1   4.143            0
12    2016      1    2   4.143            0
13    2016      1    3   4.143            0
14    2016      1    4   4.143            0
15    2016      1    5   4.192            0
16    2016      1    6   4.192            0
17    2016      1    7   4.285            0
18    2016      1    8   4.285            0
19    2016      1    9   4.285            0
20    2016      1   10   4.333            0
21    2016      1   11   4.379            0
22    2016      1   12   4.428            0
23    2016      1   13   4.428            0
24    2016      1   14   4.474            0
25    2016      1   15   4.520            0
26    2016      1   16   4.565            0
27    2016      1   17   4.615            0
28    2016      1   18   4.662            0
29    2016      1   19   4.662            0
...    ...    ...  ...     ...          ...         ...        ...
1219  2019      4   23   3.345            0
1220  2019      4   24  11.062            0
1221  2019      4   25  16.213            0
1222  2019      4   26  18.494            0
1223  2019      4   27  18.379            0
1224  2019      4   28  18.337            0
1225  2019      4   29  18.209            0
1226  2019      4   30  17.662            0
1227  2019      5    1  17.645            0
1228  2019      5    2   9.668            0
1229  2019      5    3  12.530            0
1230  2019      5    4  13.956            0
1231  2019      5    5  14.730            0
1232  2019      5    6   9.059            0
1233  2019      5    7  12.027            0
1234  2019      5    8   4.435            0
1235  2019      5    9  12.837            0
1236  2019      5   10   8.736            0
1237  2019      5   11  12.324            0
1238  2019      5   12  11.567            0
1239  2019      5   13  13.052            0
1240  2019      5   14  10.581            0
1241  2019      5   15  15.427            0
1242  2019      5   16  16.622            0
1243  2019      5   17  13.259            0
1244  2019      5   18  10.435            0
1245  2019      5   19  16.372            0
1246  2019      5   20  13.805            0
1247  2019      5   21  14.940            0
1248  2019      5   22  11.620            0

[1249 rows x 7 columns]

In [27]:
kogl_denali_park_new['Interpolate']=0
kogl_denali_park_new['DC Capacity']= ""
kogl_denali_park_new['Location']= ""
kogl_denali_park_new['DC Capacity'][0]=4
kogl_denali_park_new['Location'][0]='Denali park'
kogl_denali_park_new.to_csv('kogl_denali_park_new',index=False)
kogl_denali_park_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity     Location
0    2016      9   29   6.088            0           4  Denali park
1    2016      9   30  13.221            0
2    2016     10    1  11.792            0
3    2016     10    2   2.687            0
4    2016     10    3   1.996            0
5    2016     10    4   2.464            0
6    2016     10    5  11.567            0
7    2016     10    6  11.758            0
8    2016     10    7  11.085            0
9    2016     10    8  10.699            0
10   2016     10    9   9.084            0
11   2016     10   10   5.467            0
12   2016     10   11   8.086            0
13   2016     10   12   9.058            0
14   2016     10   13   8.727            0
15   2016     10   14   8.511            0
16   2016     10   15   8.509            0
17   2016     10   16   7.967            0
18   2016     10   17   4.836            0
19   2016     10   18   6.035            0
20   2016     10   19   3.637            0
21   2016     10   20   0.971            0
22   2016     10   21   0.034            0
23   2016     10   22   5.725            0
24   2016     10   23   5.830            0
25   2016     10   24   5.518            0
26   2016     10   25   5.013            0
27   2016     10   26   3.687            0
28   2016     10   27   4.320            0
29   2016     10   28   3.325            0
..    ...    ...  ...     ...          ...         ...          ...
936  2019      4   23  19.009            0
937  2019      4   24  25.647            0
938  2019      4   25  25.792            0
939  2019      4   26  17.202            0
940  2019      4   27  26.275            0
941  2019      4   28  26.299            0
942  2019      4   29  26.217            0
943  2019      4   30  25.881            0
944  2019      5    1  24.088            0
945  2019      5    2   9.797            0
946  2019      5    3  10.876            0
947  2019      5    4  15.230            0
948  2019      5    5  15.658            0
949  2019      5    6  14.800            0
950  2019      5    7  16.370            0
951  2019      5    8   9.109            0
952  2019      5    9  15.542            0
953  2019      5   10  18.102            0
954  2019      5   11  10.783            0
955  2019      5   12  13.194            0
956  2019      5   13  16.250            0
957  2019      5   14  21.424            0
958  2019      5   15  20.533            0
959  2019      5   16  13.024            0
960  2019      5   17  21.821            0
961  2019      5   18   8.561            0
962  2019      5   19  22.784            0
963  2019      5   20  22.181            0
964  2019      5   21  19.962            0
965  2019      5   22  22.698            0

[966 rows x 7 columns]

In [28]:
ronlevy_Soldotna_new['Interpolate']=0
ronlevy_Soldotna_new['DC Capacity']= ""
ronlevy_Soldotna_new['Location']= ""
ronlevy_Soldotna_new['DC Capacity'][0]=7.6
ronlevy_Soldotna_new['Location'][0]='Soldotna'
ronlevy_Soldotna_new.to_csv('ronlevy_Soldotna_new',index=False)
ronlevy_Soldotna_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

      Year  Month  Day  Energy  Interpolate DC Capacity  Location
0     2011      8   31   0.003            0         7.6  Soldotna
1     2011      9    1  31.842            0
2     2011      9    2  12.791            0
3     2011      9    3  18.911            0
4     2011      9    4  12.243            0
5     2011      9    5  11.956            0
6     2011      9    6   9.133            0
7     2011      9    7   4.745            0
8     2011      9    8  28.046            0
9     2011      9    9  39.240            0
10    2011      9   10  32.258            0
11    2011      9   11  23.332            0
12    2011      9   12   6.808            0
13    2011      9   13  18.896            0
14    2011      9   14  20.115            0
15    2011      9   15   5.761            0
16    2011      9   16   4.331            0
17    2011      9   17  17.698            0
18    2011      9   18  21.328            0
19    2011      9   19   4.555            0
20    2011      9   20   9.089            0
21    2011      9   21  15.808            0
22    2011      9   22  13.335            0
23    2011      9   23  22.243            0
24    2011      9   24  18.150            0
25    2011      9   25  22.739            0
26    2011      9   26  19.309            0
27    2011      9   27  25.980            0
28    2011      9   28  25.426            0
29    2011      9   29  11.025            0
...    ...    ...  ...     ...          ...         ...       ...
2792  2019      4   23  36.883            0
2793  2019      4   24  27.706            0
2794  2019      4   25  30.803            0
2795  2019      4   26  50.031            0
2796  2019      4   27  49.638            0
2797  2019      4   28  40.883            0
2798  2019      4   29  20.970            0
2799  2019      4   30  25.339            0
2800  2019      5    1  30.375            0
2801  2019      5    2  16.992            0
2802  2019      5    3  48.859            0
2803  2019      5    4  44.257            0
2804  2019      5    5  12.949            0
2805  2019      5    6  20.922            0
2806  2019      5    7  29.873            0
2807  2019      5    8  28.318            0
2808  2019      5    9  16.912            0
2809  2019      5   10  12.770            0
2810  2019      5   11  23.881            0
2811  2019      5   12  21.766            0
2812  2019      5   13  18.618            0
2813  2019      5   14  34.340            0
2814  2019      5   15  22.412            0
2815  2019      5   16  29.449            0
2816  2019      5   17  27.504            0
2817  2019      5   18  22.384            0
2818  2019      5   19  25.260            0
2819  2019      5   20  21.122            0
2820  2019      5   21  46.941            0
2821  2019      5   22  26.419            0

[2822 rows x 7 columns]

In [29]:
albin_fairbanks_new['Interpolate']=0
albin_fairbanks_new['DC Capacity']= ""
albin_fairbanks_new['Location']= ""
albin_fairbanks_new['DC Capacity'][0]=4
albin_fairbanks_new['Location'][0]='Fairbanks'
albin_fairbanks_new.to_csv('albin_fairbanks_new',index=False)
albin_fairbanks_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

      Year  Month  Day  Energy  Interpolate DC Capacity   Location
0     2014      7   29  18.996            0           4  Fairbanks
1     2014      7   30  18.455            0
2     2014      7   31  11.325            0
3     2014      8    1   1.626            0
4     2014      8    2   1.560            0
5     2014      8    3  12.551            0
6     2014      8    4  11.741            0
7     2014      8    5   2.715            0
8     2014      8    6  17.609            0
9     2014      8    7  19.814            0
10    2014      8    8  19.571            0
11    2014      8    9  15.401            0
12    2014      8   10  13.545            0
13    2014      8   11  15.802            0
14    2014      8   12   4.861            0
15    2014      8   13  16.169            0
16    2014      8   14  16.841            0
17    2014      8   15   9.016            0
18    2014      8   16  10.255            0
19    2014      8   17   3.630            0
20    2014      8   18  11.503            0
21    2014      8   19   8.351            0
22    2014      8   20  10.694            0
23    2014      8   21  11.558            0
24    2014      8   22  17.001            0
25    2014      8   23  14.981            0
26    2014      8   24  15.915            0
27    2014      8   25   7.675            0
28    2014      8   26   8.252            0
29    2014      8   27  12.593            0
...    ...    ...  ...     ...          ...         ...        ...
1729  2019      4   23   0.407            0
1730  2019      4   24  11.748            0
1731  2019      4   25  18.050            0
1732  2019      4   26  24.227            0
1733  2019      4   27  23.480            0
1734  2019      4   28  23.540            0
1735  2019      4   29  23.263            0
1736  2019      4   30  22.591            0
1737  2019      5    1  22.627            0
1738  2019      5    2  12.015            0
1739  2019      5    3  12.897            0
1740  2019      5    4  15.536            0
1741  2019      5    5  17.807            0
1742  2019      5    6   9.672            0
1743  2019      5    7  14.693            0
1744  2019      5    8   4.327            0
1745  2019      5    9  18.883            0
1746  2019      5   10   8.099            0
1747  2019      5   11  15.806            0
1748  2019      5   12  18.833            0
1749  2019      5   13  16.181            0
1750  2019      5   14  13.600            0
1751  2019      5   15  18.438            0
1752  2019      5   16  22.564            0
1753  2019      5   17  15.874            0
1754  2019      5   18  11.984            0
1755  2019      5   19  18.447            0
1756  2019      5   20  18.015            0
1757  2019      5   21  20.976            0
1758  2019      5   22  13.462            0

[1759 rows x 7 columns]

In [30]:
wiessman_fairbanks_new['Interpolate']=0
wiessman_fairbanks_new['DC Capacity']= ""
wiessman_fairbanks_new['Location']= ""
wiessman_fairbanks_new['DC Capacity'][0]=3.1
wiessman_fairbanks_new['Location'][0]='Fairbanks'
wiessman_fairbanks_new.to_csv('wiessman_fairbanks_new',index=False)
wiessman_fairbanks_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

      Year  Month  Day  Energy  Interpolate DC Capacity   Location
0     2015      8   27   2.927            0         3.1  Fairbanks
1     2015      8   28   7.106            0
2     2015      8   29   6.720            0
3     2015      8   30  12.858            0
4     2015      8   31  11.036            0
5     2015      9    1  17.431            0
6     2015      9    2  19.792            0
7     2015      9    3  16.644            0
8     2015      9    4  16.377            0
9     2015      9    5  18.488            0
10    2015      9    6  20.350            0
11    2015      9    7  14.510            0
12    2015      9    8   8.682            0
13    2015      9    9   8.949            0
14    2015      9   10   8.961            0
15    2015      9   11  13.280            0
16    2015      9   12   4.609            0
17    2015      9   13   1.953            0
18    2015      9   14   3.047            0
19    2015      9   15   4.078            0
20    2015      9   16   3.011            0
21    2015      9   17   3.016            0
22    2015      9   18   3.909            0
23    2015      9   19   3.541            0
24    2015      9   20   4.014            0
25    2015      9   21   4.243            0
26    2015      9   22   8.517            0
27    2015      9   23   5.417            0
28    2015      9   24  17.821            0
29    2015      9   25   0.596            0
...    ...    ...  ...     ...          ...         ...        ...
1335  2019      4   23   3.508            0
1336  2019      4   24  17.846            0
1337  2019      4   25  21.460            0
1338  2019      4   26  21.563            0
1339  2019      4   27  21.442            0
1340  2019      4   28  21.607            0
1341  2019      4   29  21.576            0
1342  2019      4   30  20.984            0
1343  2019      5    1  20.817            0
1344  2019      5    2  12.399            0
1345  2019      5    3  11.736            0
1346  2019      5    4  14.538            0
1347  2019      5    5  20.888            0
1348  2019      5    6  11.974            0
1349  2019      5    7  17.452            0
1350  2019      5    8   5.904            0
1351  2019      5    9  21.282            0
1352  2019      5   10  10.988            0
1353  2019      5   11  13.557            0
1354  2019      5   12  19.729            0
1355  2019      5   13  14.954            0
1356  2019      5   14  13.586            0
1357  2019      5   15  21.436            0
1358  2019      5   16  22.427            0
1359  2019      5   17  22.201            0
1360  2019      5   18  14.843            0
1361  2019      5   19  19.879            0
1362  2019      5   20  17.119            0
1363  2019      5   21  20.463            0
1364  2019      5   22  17.326            0

[1365 rows x 7 columns]