In [29]:
import pandas as pd
import numpy as np
from the_needed_function import drop_the_hours
from the_needed_function import seperate_date

In [30]:
breeze_Anchorage = pd.read_csv('../Cleaned_data/data/309Breeze.csv')
huffman_Anchorage = pd.read_csv('../Cleaned_data/data/12800Huffman.csv')
tahneeta_Anchorage = pd.read_csv('../Cleaned_data/data/10611Tahneeta.csv')
wildwood_Anchorage = pd.read_csv('../Cleaned_data/data/1957Wildwood.csv')
alumni_Anchorage = pd.read_csv('../Cleaned_data/data/3800Alumni.csv')

tedrow_Eagle_river = pd.read_csv('../Cleaned_data/data/18306Tedrow.csv')

trailways_Chickaloon = pd.read_csv('../Cleaned_data/data/34738Trailways.csv')

glennhill_Chugiak = pd.read_csv('../Cleaned_data/data/23221GlennHill.csv')

westlake_palmer = pd.read_csv('../Cleaned_data/data/3700Westlake.csv')
biscane_palmer = pd.read_csv('../Cleaned_data/data/1232Biscane.csv')
mckeen_palmer = pd.read_csv('../Cleaned_data/data/4700McKeen.csv')
farmloop_palmer = pd.read_csv('../Cleaned_data/data/4700FarmLoop.csv')
alask_palmer = pd.read_csv('../Cleaned_data/data/550S_Alaska.csv')
fishhood_palmer = pd.read_csv('../Cleaned_data/data/5200N_PalmerFishhook.csv')

redfox_wasilla = pd.read_csv('../Cleaned_data/data/2150E_RedFox.csv')
countryfield_wasilla = pd.read_csv('../Cleaned_data/data/4048E_CountryFieldCircle.csv')
reliance_wasilla = pd.read_csv('../Cleaned_data/data/5007Reliance.csv')

woodside_homer = pd.read_csv('../Cleaned_data/data/326Woodside.csv')

In [31]:
def drop_the_hours (dataframe):
    """This function is to drop the hours in the first columns of the daily data
    
       Arg:
       dataframe(string):The name of the dataframe that you want to change
       
       Return:
       the dataframe after changed
    """
    
    date_time = []
    
    for i in range(len(dataframe)):
        date_time.append(dataframe['Date/Time'][i].rsplit(' ',2)[0])
    
    dataframe['Date/Time']=date_time
    dataframe.drop(dataframe.tail(1).index,inplace=True)
    
    return(dataframe)

def seperate_date(dataframe):
    """This function will create a new dataframe that contains the columns in order of 'Year','Month','Day','Energy'
    
       Args:
       dataframeï¼ˆstring):The name of the dataframe contain the data you want to use
       
       Return:
       A new dataframe
    """
    
    dataframe_new = pd.DataFrame(columns=['Year','Month','Day','Energy'])
    year=[]
    month=[]
    day=[]
    energy=[]
    
    for i in range(len(dataframe)):
        year.append(int(dataframe['Date/Time'][i].rsplit('-',2)[0]))
        month.append(int(dataframe['Date/Time'][i].rsplit('-',2)[1]))
        day.append(int(dataframe['Date/Time'][i].rsplit('-',2)[2]))
        energy.append(dataframe['Energy Produced (Wh)'][i]/1000)
    
    dataframe_new['Year']=year
    dataframe_new['Month']=month
    dataframe_new['Day']=day
    dataframe_new['Energy'] = energy
    
    return(dataframe_new)

In [32]:
drop_the_hours(breeze_Anchorage)
drop_the_hours(huffman_Anchorage)
drop_the_hours(tahneeta_Anchorage)
drop_the_hours(wildwood_Anchorage)
drop_the_hours(alumni_Anchorage)

      Date/Time  Energy Produced (Wh)
0    2018-02-21                   687
1    2018-02-22                  3993
2    2018-02-23                 12196
3    2018-02-24                  6938
4    2018-02-25                 11990
5    2018-02-26                  1320
6    2018-02-27                 13090
7    2018-02-28                 16523
8    2018-03-01                 15651
9    2018-03-02                  2936
10   2018-03-03                  1788
11   2018-03-04                  4259
12   2018-03-05                  5425
13   2018-03-06                  2353
14   2018-03-07                  8859
15   2018-03-08                  1320
16   2018-03-09                  3731
17   2018-03-10                 10126
18   2018-03-11                  2656
19   2018-03-12                 11139
20   2018-03-13                 10171
21   2018-03-14                  4205
22   2018-03-15                  7131
23   2018-03-16                  1921
24   2018-03-17                  7013
25   2018-03-18                  3313
26   2018-03-19                  9121
27   2018-03-20                 15235
28   2018-03-21                 16833
29   2018-03-22                 16636
..          ...                   ...
399  2019-03-27                  3888
400  2019-03-28                 13828
401  2019-03-29                 12353
402  2019-03-30                 13991
403  2019-03-31                 13397
404  2019-04-01                 13967
405  2019-04-02                   238
406  2019-04-03                     0
407  2019-04-04                     0
408  2019-04-05                     0
409  2019-04-06                     0
410  2019-04-07                     0
411  2019-04-08                     0
412  2019-04-09                     0
413  2019-04-10                     0
414  2019-04-11                     0
415  2019-04-12                     0
416  2019-04-13                     0
417  2019-04-14                     0
418  2019-04-15                     0
419  2019-04-16                     0
420  2019-04-17                     0
421  2019-04-18                     0
422  2019-04-19                     0
423  2019-04-20                     0
424  2019-04-21                     0
425  2019-04-22                     0
426  2019-04-23                     0
427  2019-04-24                     0
428  2019-04-25                     0

[429 rows x 2 columns]

In [33]:
breeze_Anchorage_new = seperate_date(breeze_Anchorage)
huffman_Anchorage_new = seperate_date(huffman_Anchorage)
tahneeta_Anchorage_new = seperate_date(tahneeta_Anchorage)
wildwood_Anchorage_new = seperate_date(wildwood_Anchorage)
alumni_Anchorage_new = seperate_date(alumni_Anchorage)

In [35]:
breeze_Anchorage_new['Interpolate']=0
breeze_Anchorage_new['DC Capacity']= ""
breeze_Anchorage_new['Location']= ""
breeze_Anchorage_new['DC Capacity'][0]=2.9
breeze_Anchorage_new['Location'][0]='Anchorage'
breeze_Anchorage_new.to_csv('breeze_Anchorage_new',index=False)
breeze_Anchorage_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity   Location
0    2017      2    5   0.037            0         2.9  Anchorage
1    2017      2    6   0.119            0
2    2017      2    7   0.141            0
3    2017      2    8   0.223            0
4    2017      2    9   0.038            0
5    2017      2   10   0.053            0
6    2017      2   11   0.139            0
7    2017      2   12   0.000            0
8    2017      2   13   0.008            0
9    2017      2   14   0.011            0
10   2017      2   15   0.000            0
11   2017      2   16   0.000            0
12   2017      2   17   0.000            0
13   2017      2   18   0.000            0
14   2017      2   19   0.000            0
15   2017      2   20   0.000            0
16   2017      2   21   0.000            0
17   2017      2   22   0.000            0
18   2017      2   23   0.000            0
19   2017      2   24   0.000            0
20   2017      2   25   0.000            0
21   2017      2   26   0.000            0
22   2017      2   27   0.000            0
23   2017      2   28   0.000            0
24   2017      3    1   0.000            0
25   2017      3    2   0.004            0
26   2017      3    3   0.010            0
27   2017      3    4   0.011            0
28   2017      3    5   0.013            0
29   2017      3    6   0.016            0
..    ...    ...  ...     ...          ...         ...        ...
780  2019      3   27   4.027            0
781  2019      3   28   7.798            0
782  2019      3   29   8.427            0
783  2019      3   30   8.451            0
784  2019      3   31   8.658            0
785  2019      4    1   8.859            0
786  2019      4    2   6.771            0
787  2019      4    3   9.383            0
788  2019      4    4   5.049            0
789  2019      4    5   9.514            0
790  2019      4    6   8.294            0
791  2019      4    7   4.106            0
792  2019      4    8   7.585            0
793  2019      4    9   7.441            0
794  2019      4   10   9.732            0
795  2019      4   11   3.870            0
796  2019      4   12   7.272            0
797  2019      4   13   9.947            0
798  2019      4   14  11.854            0
799  2019      4   15  11.352            0
800  2019      4   16   5.905            0
801  2019      4   17   3.423            0
802  2019      4   18   3.776            0
803  2019      4   19   4.869            0
804  2019      4   20   3.903            0
805  2019      4   21   0.000            0
806  2019      4   22   0.000            0
807  2019      4   23   0.000            0
808  2019      4   24   0.000            0
809  2019      4   25   0.000            0

[810 rows x 7 columns]

In [36]:
huffman_Anchorage_new['Interpolate']=0
huffman_Anchorage_new['DC Capacity']= ""
huffman_Anchorage_new['Location']= ""
huffman_Anchorage_new['DC Capacity'][0]=3.6
huffman_Anchorage_new['Location'][0]='Anchorage'
huffman_Anchorage_new.to_csv('huffman_Anchorage_new',index=False)
huffman_Anchorage_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity   Location
0    2017      5   31  11.641            0         3.6  Anchorage
1    2017      6    1  24.026            0
2    2017      6    2  23.821            0
3    2017      6    3  21.138            0
4    2017      6    4   8.250            0
5    2017      6    5  11.954            0
6    2017      6    6   9.448            0
7    2017      6    7  12.548            0
8    2017      6    8  10.296            0
9    2017      6    9  13.886            0
10   2017      6   10   3.780            0
11   2017      6   11  15.732            0
12   2017      6   12   8.745            0
13   2017      6   13  18.599            0
14   2017      6   14  15.375            0
15   2017      6   15  25.663            0
16   2017      6   16  25.352            0
17   2017      6   17  16.946            0
18   2017      6   18  16.824            0
19   2017      6   19   9.857            0
20   2017      6   20   9.014            0
21   2017      6   21  14.615            0
22   2017      6   22   7.358            0
23   2017      6   23   7.739            0
24   2017      6   24  20.329            0
25   2017      6   25  21.924            0
26   2017      6   26  11.178            0
27   2017      6   27   5.294            0
28   2017      6   28  16.095            0
29   2017      6   29   4.643            0
..    ...    ...  ...     ...          ...         ...        ...
665  2019      3   27   5.852            0
666  2019      3   28  15.048            0
667  2019      3   29  13.552            0
668  2019      3   30  13.743            0
669  2019      3   31  15.571            0
670  2019      4    1  16.167            0
671  2019      4    2  11.175            0
672  2019      4    3  16.775            0
673  2019      4    4  10.424            0
674  2019      4    5  15.712            0
675  2019      4    6  11.141            0
676  2019      4    7   6.633            0
677  2019      4    8   9.659            0
678  2019      4    9   9.443            0
679  2019      4   10  13.793            0
680  2019      4   11   4.040            0
681  2019      4   12  10.594            0
682  2019      4   13  14.089            0
683  2019      4   14  19.166            0
684  2019      4   15  18.450            0
685  2019      4   16   9.317            0
686  2019      4   17   4.011            0
687  2019      4   18   4.793            0
688  2019      4   19   7.086            0
689  2019      4   20  10.058            0
690  2019      4   21   8.045            0
691  2019      4   22   0.283            0
692  2019      4   23   7.983            0
693  2019      4   24  13.167            0
694  2019      4   25  15.808            0

[695 rows x 7 columns]

In [37]:
tahneeta_Anchorage_new['Interpolate']=0
tahneeta_Anchorage_new['DC Capacity']= ""
tahneeta_Anchorage_new['Location']= ""
tahneeta_Anchorage_new['DC Capacity'][0]=3
tahneeta_Anchorage_new['Location'][0]='Anchorage'
tahneeta_Anchorage_new.to_csv('tahneeta_Anchorage_new',index=False)
tahneeta_Anchorage_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity   Location
0    2017      6    2  11.130            0           3  Anchorage
1    2017      6    3  19.115            0
2    2017      6    4   5.566            0
3    2017      6    5  13.087            0
4    2017      6    6   7.775            0
5    2017      6    7   7.973            0
6    2017      6    8   7.224            0
7    2017      6    9  10.031            0
8    2017      6   10   2.767            0
9    2017      6   11  16.037            0
10   2017      6   12   6.970            0
11   2017      6   13  10.668            0
12   2017      6   14  15.570            0
13   2017      6   15  19.753            0
14   2017      6   16  16.504            0
15   2017      6   17  13.172            0
16   2017      6   18  12.448            0
17   2017      6   19   7.162            0
18   2017      6   20   6.454            0
19   2017      6   21   9.937            0
20   2017      6   22   3.517            0
21   2017      6   23   4.961            0
22   2017      6   24  16.315            0
23   2017      6   25  17.009            0
24   2017      6   26   5.797            0
25   2017      6   27   3.742            0
26   2017      6   28   9.022            0
27   2017      6   29   3.511            0
28   2017      6   30  11.006            0
29   2017      7    1   6.476            0
..    ...    ...  ...     ...          ...         ...        ...
663  2019      3   27   3.699            0
664  2019      3   28   8.283            0
665  2019      3   29   4.483            0
666  2019      3   30   9.299            0
667  2019      3   31   9.396            0
668  2019      4    1   9.758            0
669  2019      4    2   7.317            0
670  2019      4    3  10.214            0
671  2019      4    4   4.246            0
672  2019      4    5  10.158            0
673  2019      4    6   8.345            0
674  2019      4    7   3.498            0
675  2019      4    8   5.933            0
676  2019      4    9   5.814            0
677  2019      4   10   6.781            0
678  2019      4   11   2.827            0
679  2019      4   12   7.894            0
680  2019      4   13  10.674            0
681  2019      4   14  11.275            0
682  2019      4   15  11.821            0
683  2019      4   16   4.761            0
684  2019      4   17   2.224            0
685  2019      4   18   1.999            0
686  2019      4   19   4.585            0
687  2019      4   20   3.011            0
688  2019      4   21   4.529            0
689  2019      4   22   0.155            0
690  2019      4   23   4.344            0
691  2019      4   24   7.415            0
692  2019      4   25  11.631            0

[693 rows x 7 columns]

In [38]:
wildwood_Anchorage_new['Interpolate']=0
wildwood_Anchorage_new['DC Capacity']= ""
wildwood_Anchorage_new['Location']= ""
wildwood_Anchorage_new['DC Capacity'][0]=5.1
wildwood_Anchorage_new['Location'][0]='Anchorage'
wildwood_Anchorage_new.to_csv('wildwood_Anchorage_new',index=False)
wildwood_Anchorage_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity   Location
0    2017      6    7   9.874            0         5.1  Anchorage
1    2017      6    8  16.312            0
2    2017      6    9  18.373            0
3    2017      6   10   5.251            0
4    2017      6   11  20.687            0
5    2017      6   12  13.428            0
6    2017      6   13  26.944            0
7    2017      6   14  26.429            0
8    2017      6   15  35.032            0
9    2017      6   16  33.873            0
10   2017      6   17  31.636            0
11   2017      6   18  33.077            0
12   2017      6   19  15.030            0
13   2017      6   20  12.209            0
14   2017      6   21  17.824            0
15   2017      6   22  13.103            0
16   2017      6   23  15.920            0
17   2017      6   24  28.399            0
18   2017      6   25  30.465            0
19   2017      6   26  17.837            0
20   2017      6   27   8.944            0
21   2017      6   28  19.836            0
22   2017      6   29   7.938            0
23   2017      6   30  21.497            0
24   2017      7    1  17.135            0
25   2017      7    2   7.904            0
26   2017      7    3   7.613            0
27   2017      7    4  31.881            0
28   2017      7    5  27.146            0
29   2017      7    6  28.756            0
..    ...    ...  ...     ...          ...         ...        ...
658  2019      3   27   8.226            0
659  2019      3   28  17.156            0
660  2019      3   29  18.254            0
661  2019      3   30  18.797            0
662  2019      3   31  19.016            0
663  2019      4    1  19.880            0
664  2019      4    2  15.420            0
665  2019      4    3  21.307            0
666  2019      4    4  10.623            0
667  2019      4    5  20.622            0
668  2019      4    6  13.133            0
669  2019      4    7   9.601            0
670  2019      4    8  14.149            0
671  2019      4    9  14.416            0
672  2019      4   10  24.147            0
673  2019      4   11   7.841            0
674  2019      4   12  15.454            0
675  2019      4   13  18.491            0
676  2019      4   14  25.687            0
677  2019      4   15  26.134            0
678  2019      4   16  11.643            0
679  2019      4   17   6.513            0
680  2019      4   18   7.171            0
681  2019      4   19   1.405            0
682  2019      4   20   9.936            0
683  2019      4   21   5.243            0
684  2019      4   22   1.622            0
685  2019      4   23   9.005            0
686  2019      4   24  14.915            0
687  2019      4   25  22.509            0

[688 rows x 7 columns]

In [39]:
alumni_Anchorage_new['Interpolate']=0
alumni_Anchorage_new['DC Capacity']= ""
alumni_Anchorage_new['Location']= ""
alumni_Anchorage_new['DC Capacity'][0]=2.6
alumni_Anchorage_new['Location'][0]='Anchorage'
alumni_Anchorage_new.to_csv('alumni_Anchorage_new',index=False)
alumni_Anchorage_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity   Location
0    2018      2   21   0.687            0         2.6  Anchorage
1    2018      2   22   3.993            0
2    2018      2   23  12.196            0
3    2018      2   24   6.938            0
4    2018      2   25  11.990            0
5    2018      2   26   1.320            0
6    2018      2   27  13.090            0
7    2018      2   28  16.523            0
8    2018      3    1  15.651            0
9    2018      3    2   2.936            0
10   2018      3    3   1.788            0
11   2018      3    4   4.259            0
12   2018      3    5   5.425            0
13   2018      3    6   2.353            0
14   2018      3    7   8.859            0
15   2018      3    8   1.320            0
16   2018      3    9   3.731            0
17   2018      3   10  10.126            0
18   2018      3   11   2.656            0
19   2018      3   12  11.139            0
20   2018      3   13  10.171            0
21   2018      3   14   4.205            0
22   2018      3   15   7.131            0
23   2018      3   16   1.921            0
24   2018      3   17   7.013            0
25   2018      3   18   3.313            0
26   2018      3   19   9.121            0
27   2018      3   20  15.235            0
28   2018      3   21  16.833            0
29   2018      3   22  16.636            0
..    ...    ...  ...     ...          ...         ...        ...
399  2019      3   27   3.888            0
400  2019      3   28  13.828            0
401  2019      3   29  12.353            0
402  2019      3   30  13.991            0
403  2019      3   31  13.397            0
404  2019      4    1  13.967            0
405  2019      4    2   0.238            0
406  2019      4    3   0.000            0
407  2019      4    4   0.000            0
408  2019      4    5   0.000            0
409  2019      4    6   0.000            0
410  2019      4    7   0.000            0
411  2019      4    8   0.000            0
412  2019      4    9   0.000            0
413  2019      4   10   0.000            0
414  2019      4   11   0.000            0
415  2019      4   12   0.000            0
416  2019      4   13   0.000            0
417  2019      4   14   0.000            0
418  2019      4   15   0.000            0
419  2019      4   16   0.000            0
420  2019      4   17   0.000            0
421  2019      4   18   0.000            0
422  2019      4   19   0.000            0
423  2019      4   20   0.000            0
424  2019      4   21   0.000            0
425  2019      4   22   0.000            0
426  2019      4   23   0.000            0
427  2019      4   24   0.000            0
428  2019      4   25   0.000            0

[429 rows x 7 columns]

In [40]:
drop_the_hours(tedrow_Eagle_river)
drop_the_hours(trailways_Chickaloon)
drop_the_hours(glennhill_Chugiak)

tedrow_Eagle_river_new = seperate_date(tedrow_Eagle_river)
trailways_Chickaloon_new = seperate_date(trailways_Chickaloon)
glennhill_Chugiak_new = seperate_date(glennhill_Chugiak)

In [45]:
tedrow_Eagle_river_new['Interpolate']=0
tedrow_Eagle_river_new['DC Capacity']= ""
tedrow_Eagle_river_new['Location']= ""
tedrow_Eagle_river_new['DC Capacity'][0]=6
tedrow_Eagle_river_new['Location'][0]='Eagle River'
tedrow_Eagle_river_new.to_csv('tedrow_Eagle_river_new',index=False)
tedrow_Eagle_river_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity     Location
0    2017      8    7   2.154            0           6  Eagle River
1    2017      8    8  22.420            0
2    2017      8    9   9.000            0
3    2017      8   10  13.450            0
4    2017      8   11  10.060            0
5    2017      8   12   8.297            0
6    2017      8   13  15.120            0
7    2017      8   14  15.713            0
8    2017      8   15  16.965            0
9    2017      8   16   6.130            0
10   2017      8   17  11.758            0
11   2017      8   18   7.930            0
12   2017      8   19  18.234            0
13   2017      8   20   6.505            0
14   2017      8   21   6.276            0
15   2017      8   22  26.501            0
16   2017      8   23   6.330            0
17   2017      8   24   8.041            0
18   2017      8   25  13.346            0
19   2017      8   26  21.856            0
20   2017      8   27  20.131            0
21   2017      8   28  16.077            0
22   2017      8   29  10.042            0
23   2017      8   30  13.266            0
24   2017      8   31   5.249            0
25   2017      9    1  13.784            0
26   2017      9    2  15.654            0
27   2017      9    3   4.214            0
28   2017      9    4  18.862            0
29   2017      9    5   3.105            0
..    ...    ...  ...     ...          ...         ...          ...
597  2019      3   27   7.721            0
598  2019      3   28  23.987            0
599  2019      3   29  13.412            0
600  2019      3   30  26.006            0
601  2019      3   31  25.593            0
602  2019      4    1  26.398            0
603  2019      4    2  23.916            0
604  2019      4    3  27.442            0
605  2019      4    4  11.674            0
606  2019      4    5  26.665            0
607  2019      4    6  16.943            0
608  2019      4    7  13.643            0
609  2019      4    8  16.473            0
610  2019      4    9  13.411            0
611  2019      4   10  20.247            0
612  2019      4   11   8.284            0
613  2019      4   12  15.281            0
614  2019      4   13  26.183            0
615  2019      4   14  25.041            0
616  2019      4   15  25.989            0
617  2019      4   16  11.510            0
618  2019      4   17   3.530            0
619  2019      4   18   6.521            0
620  2019      4   19  14.654            0
621  2019      4   20   9.290            0
622  2019      4   21  23.680            0
623  2019      4   22   5.050            0
624  2019      4   23  11.397            0
625  2019      4   24  27.037            0
626  2019      4   25  26.499            0

[627 rows x 7 columns]

In [46]:
trailways_Chickaloon_new['Interpolate']=0
trailways_Chickaloon_new['DC Capacity']= ""
trailways_Chickaloon_new['Location']= ""
trailways_Chickaloon_new['DC Capacity'][0]=3.2
trailways_Chickaloon_new['Location'][0]='Chickaloon'
trailways_Chickaloon_new.to_csv('trailways_Chickaloon_new',index=False)
trailways_Chickaloon_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity    Location
0    2017      8   25   2.444            0         3.2  Chickaloon
1    2017      8   26   7.929            0
2    2017      8   27   8.867            0
3    2017      8   28  12.867            0
4    2017      8   29   4.145            0
5    2017      8   30   5.118            0
6    2017      8   31   3.928            0
7    2017      9    1  12.470            0
8    2017      9    2  11.193            0
9    2017      9    3   3.515            0
10   2017      9    4  17.137            0
11   2017      9    5   1.355            0
12   2017      9    6   2.039            0
13   2017      9    7   5.795            0
14   2017      9    8   8.521            0
15   2017      9    9   9.154            0
16   2017      9   10   8.131            0
17   2017      9   11   9.544            0
18   2017      9   12  10.661            0
19   2017      9   13   3.965            0
20   2017      9   14   3.573            0
21   2017      9   15   5.376            0
22   2017      9   16   4.444            0
23   2017      9   17  12.388            0
24   2017      9   18   3.649            0
25   2017      9   19   8.731            0
26   2017      9   20   2.165            0
27   2017      9   21   1.784            0
28   2017      9   22   3.449            0
29   2017      9   23   1.477            0
..    ...    ...  ...     ...          ...         ...         ...
579  2019      3   27   5.036            0
580  2019      3   28  18.932            0
581  2019      3   29  18.390            0
582  2019      3   30  19.245            0
583  2019      3   31  17.305            0
584  2019      4    1  18.807            0
585  2019      4    2  15.286            0
586  2019      4    3  19.974            0
587  2019      4    4  11.610            0
588  2019      4    5  17.956            0
589  2019      4    6   9.965            0
590  2019      4    7  11.275            0
591  2019      4    8  14.396            0
592  2019      4    9  17.784            0
593  2019      4   10  19.465            0
594  2019      4   11   4.213            0
595  2019      4   12   9.554            0
596  2019      4   13  15.429            0
597  2019      4   14  15.210            0
598  2019      4   15  19.472            0
599  2019      4   16  14.102            0
600  2019      4   17   3.170            0
601  2019      4   18  12.078            0
602  2019      4   19  11.417            0
603  2019      4   20  10.995            0
604  2019      4   21   9.392            0
605  2019      4   22   4.719            0
606  2019      4   23  14.878            0
607  2019      4   24  17.964            0
608  2019      4   25  18.248            0

[609 rows x 7 columns]

In [47]:
glennhill_Chugiak_new['Interpolate']=0
glennhill_Chugiak_new['DC Capacity']= ""
glennhill_Chugiak_new['Location']= ""
glennhill_Chugiak_new['DC Capacity'][0]=2.5
glennhill_Chugiak_new['Location'][0]='Chugiak'
glennhill_Chugiak_new.to_csv('glennhill_Chugiak_new',index=False)
glennhill_Chugiak_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity Location
0    2017      9   29   2.550            0         2.5  Chugiak
1    2017      9   30   9.924            0
2    2017     10    1   6.391            0
3    2017     10    2   3.254            0
4    2017     10    3   3.822            0
5    2017     10    4   2.074            0
6    2017     10    5   1.142            0
7    2017     10    6   4.287            0
8    2017     10    7   5.617            0
9    2017     10    8   1.512            0
10   2017     10    9   8.257            0
11   2017     10   10   1.860            0
12   2017     10   11   1.812            0
13   2017     10   12   0.731            0
14   2017     10   13   2.332            0
15   2017     10   14   4.180            0
16   2017     10   15   5.194            0
17   2017     10   16   7.827            0
18   2017     10   17   5.405            0
19   2017     10   18   7.429            0
20   2017     10   19   7.875            0
21   2017     10   20   7.528            0
22   2017     10   21   1.418            0
23   2017     10   22   5.013            0
24   2017     10   23   0.961            0
25   2017     10   24   1.100            0
26   2017     10   25   0.389            0
27   2017     10   26   0.288            0
28   2017     10   27   1.649            0
29   2017     10   28   1.548            0
..    ...    ...  ...     ...          ...         ...      ...
544  2019      3   27   5.236            0
545  2019      3   28  12.219            0
546  2019      3   29   9.619            0
547  2019      3   30  12.354            0
548  2019      3   31  11.659            0
549  2019      4    1  12.514            0
550  2019      4    2  11.104            0
551  2019      4    3  12.960            0
552  2019      4    4   6.540            0
553  2019      4    5  11.796            0
554  2019      4    6   7.539            0
555  2019      4    7   7.422            0
556  2019      4    8   8.491            0
557  2019      4    9   8.450            0
558  2019      4   10   9.366            0
559  2019      4   11   3.058            0
560  2019      4   12   4.806            0
561  2019      4   13  14.870            0
562  2019      4   14  14.455            0
563  2019      4   15  14.605            0
564  2019      4   16   6.634            0
565  2019      4   17   2.237            0
566  2019      4   18   5.228            0
567  2019      4   19   7.890            0
568  2019      4   20   7.725            0
569  2019      4   21  10.273            0
570  2019      4   22   3.766            0
571  2019      4   23   7.152            0
572  2019      4   24  13.219            0
573  2019      4   25  13.093            0

[574 rows x 7 columns]

In [48]:
drop_the_hours(westlake_palmer)
drop_the_hours(biscane_palmer)
drop_the_hours(mckeen_palmer)
drop_the_hours(farmloop_palmer)
drop_the_hours(alask_palmer)
drop_the_hours(fishhood_palmer)

westlake_palmer_new = seperate_date(westlake_palmer)
biscane_palmer_new = seperate_date(biscane_palmer)
mckeen_palmer_new = seperate_date(mckeen_palmer)
farmloop_palmer_new = seperate_date(farmloop_palmer)
alask_palmer_new = seperate_date(alask_palmer)
fishhood_palmer_new = seperate_date(fishhood_palmer)

In [49]:
westlake_palmer_new['Interpolate']=0
westlake_palmer_new['DC Capacity']= ""
westlake_palmer_new['Location']= ""
westlake_palmer_new['DC Capacity'][0]=5.1
westlake_palmer_new['Location'][0]='Palmer'
westlake_palmer_new.to_csv('westlake_palmer_new',index=False)
westlake_palmer_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity Location
0    2017     10   11   2.994            0         5.1   Palmer
1    2017     10   12   1.421            0
2    2017     10   13   4.723            0
3    2017     10   14   6.779            0
4    2017     10   15   9.683            0
5    2017     10   16  11.072            0
6    2017     10   17   5.215            0
7    2017     10   18  10.758            0
8    2017     10   19  11.298            0
9    2017     10   20  10.910            0
10   2017     10   21   3.356            0
11   2017     10   22   7.235            0
12   2017     10   23   1.708            0
13   2017     10   24   1.728            0
14   2017     10   25   0.471            0
15   2017     10   26   0.861            0
16   2017     10   27   1.244            0
17   2017     10   28   3.277            0
18   2017     10   29   0.570            0
19   2017     10   30   1.094            0
20   2017     10   31   3.409            0
21   2017     11    1   1.783            0
22   2017     11    2   5.822            0
23   2017     11    3   0.845            0
24   2017     11    4   1.680            0
25   2017     11    5   1.325            0
26   2017     11    6   3.788            0
27   2017     11    7   3.872            0
28   2017     11    8   1.955            0
29   2017     11    9   0.149            0
..    ...    ...  ...     ...          ...         ...      ...
532  2019      3   27   7.294            0
533  2019      3   28  17.038            0
534  2019      3   29  13.879            0
535  2019      3   30  17.541            0
536  2019      3   31  17.420            0
537  2019      4    1  17.543            0
538  2019      4    2  14.171            0
539  2019      4    3  19.026            0
540  2019      4    4  13.256            0
541  2019      4    5  18.213            0
542  2019      4    6  13.149            0
543  2019      4    7  10.509            0
544  2019      4    8  17.738            0
545  2019      4    9  12.426            0
546  2019      4   10  16.505            0
547  2019      4   11   4.332            0
548  2019      4   12   7.659            0
549  2019      4   13  15.741            0
550  2019      4   14  19.249            0
551  2019      4   15  17.241            0
552  2019      4   16   9.994            0
553  2019      4   17   1.682            0
554  2019      4   18   7.228            0
555  2019      4   19   3.890            0
556  2019      4   20   5.859            0
557  2019      4   21  10.370            0
558  2019      4   22   2.048            0
559  2019      4   23   6.688            0
560  2019      4   24  23.027            0
561  2019      4   25  20.570            0

[562 rows x 7 columns]

In [50]:
biscane_palmer_new['Interpolate']=0
biscane_palmer_new['DC Capacity']= ""
biscane_palmer_new['Location']= ""
biscane_palmer_new['DC Capacity'][0]=4.2
biscane_palmer_new['Location'][0]='Palmer'
biscane_palmer_new.to_csv('biscane_palmer_new',index=False)
biscane_palmer_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity Location
0    2017     10   11   2.469            0         4.2   Palmer
1    2017     10   12   1.304            0
2    2017     10   13   5.913            0
3    2017     10   14   6.983            0
4    2017     10   15  10.617            0
5    2017     10   16  12.538            0
6    2017     10   17   7.300            0
7    2017     10   18  11.257            0
8    2017     10   19  12.172            0
9    2017     10   20  11.726            0
10   2017     10   21   3.188            0
11   2017     10   22   7.671            0
12   2017     10   23   1.404            0
13   2017     10   24   1.410            0
14   2017     10   25   0.405            0
15   2017     10   26   0.728            0
16   2017     10   27   0.971            0
17   2017     10   28   2.766            0
18   2017     10   29   0.445            0
19   2017     10   30   0.916            0
20   2017     10   31   3.035            0
21   2017     11    1   1.764            0
22   2017     11    2   5.461            0
23   2017     11    3   0.855            0
24   2017     11    4   1.638            0
25   2017     11    5   0.812            0
26   2017     11    6   6.391            0
27   2017     11    7   6.318            0
28   2017     11    8   6.683            0
29   2017     11    9   0.374            0
..    ...    ...  ...     ...          ...         ...      ...
532  2019      3   27   6.387            0
533  2019      3   28  19.332            0
534  2019      3   29  12.696            0
535  2019      3   30  20.234            0
536  2019      3   31  19.821            0
537  2019      4    1  20.809            0
538  2019      4    2  15.167            0
539  2019      4    3  22.426            0
540  2019      4    4  11.299            0
541  2019      4    5  20.111            0
542  2019      4    6  12.855            0
543  2019      4    7  12.305            0
544  2019      4    8  16.614            0
545  2019      4    9  12.925            0
546  2019      4   10  19.246            0
547  2019      4   11   3.566            0
548  2019      4   12   7.017            0
549  2019      4   13  15.425            0
550  2019      4   14  17.762            0
551  2019      4   15  18.014            0
552  2019      4   16   8.450            0
553  2019      4   17   3.913            0
554  2019      4   18  11.833            0
555  2019      4   19  11.002            0
556  2019      4   20  10.671            0
557  2019      4   21   9.489            0
558  2019      4   22   2.740            0
559  2019      4   23  16.518            0
560  2019      4   24  24.171            0
561  2019      4   25  19.148            0

[562 rows x 7 columns]

In [51]:
mckeen_palmer_new['Interpolate']=0
mckeen_palmer_new['DC Capacity']= ""
mckeen_palmer_new['Location']= ""
mckeen_palmer_new['DC Capacity'][0]=6.6
mckeen_palmer_new['Location'][0]='Palmer'
mckeen_palmer_new.to_csv('mckeen_palmer_new',index=False)
mckeen_palmer_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity Location
0    2017     10   12   8.801            0         6.6   Palmer
1    2017     10   13   4.604            0
2    2017     10   14   7.374            0
3    2017     10   15   7.670            0
4    2017     10   16   7.497            0
5    2017     10   17   4.783            0
6    2017     10   18   7.292            0
7    2017     10   19   7.053            0
8    2017     10   20   6.812            0
9    2017     10   21   4.370            0
10   2017     10   22   0.467            0
11   2017     10   23   0.222            0
12   2017     10   24   0.437            0
13   2017     10   25   0.688            0
14   2017     10   26   1.210            0
15   2017     10   27   1.685            0
16   2017     10   28   3.983            0
17   2017     10   29   0.749            0
18   2017     10   30   1.468            0
19   2017     10   31   3.429            0
20   2017     11    1   2.754            0
21   2017     11    2   3.474            0
22   2017     11    3   1.476            0
23   2017     11    4   2.601            0
24   2017     11    5   0.010            0
25   2017     11    6   0.070            0
26   2017     11    7   0.441            0
27   2017     11    8   0.544            0
28   2017     11    9   0.055            0
29   2017     11   10   0.079            0
..    ...    ...  ...     ...          ...         ...      ...
531  2019      3   27  10.921            0
532  2019      3   28  19.103            0
533  2019      3   29  16.487            0
534  2019      3   30  20.311            0
535  2019      3   31  20.516            0
536  2019      4    1  20.826            0
537  2019      4    2  17.920            0
538  2019      4    3  22.671            0
539  2019      4    4  16.190            0
540  2019      4    5  21.920            0
541  2019      4    6  16.727            0
542  2019      4    7  15.203            0
543  2019      4    8  23.044            0
544  2019      4    9  15.570            0
545  2019      4   10  22.180            0
546  2019      4   11   6.149            0
547  2019      4   12  10.206            0
548  2019      4   13  20.588            0
549  2019      4   14  21.025            0
550  2019      4   15  25.263            0
551  2019      4   16  14.704            0
552  2019      4   17   0.394            0
553  2019      4   18   7.546            0
554  2019      4   19   0.229            0
555  2019      4   20   1.630            0
556  2019      4   21   9.094            0
557  2019      4   22   1.891            0
558  2019      4   23   8.669            0
559  2019      4   24  24.378            0
560  2019      4   25  28.509            0

[561 rows x 7 columns]

In [52]:
farmloop_palmer_new['Interpolate']=0
farmloop_palmer_new['DC Capacity']= ""
farmloop_palmer_new['Location']= ""
farmloop_palmer_new['DC Capacity'][0]=3.6
farmloop_palmer_new['Location'][0]='Palmer'
farmloop_palmer_new.to_csv('farmloop_palmer_new',index=False)
farmloop_palmer_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity Location
0    2017     11    9   0.041            0         3.6   Palmer
1    2017     11   10   0.350            0
2    2017     11   11   1.409            0
3    2017     11   12   1.043            0
4    2017     11   13   1.383            0
5    2017     11   14   1.824            0
6    2017     11   15   2.404            0
7    2017     11   16   0.007            0
8    2017     11   17   0.012            0
9    2017     11   18   1.048            0
10   2017     11   19   0.224            0
11   2017     11   20   1.731            0
12   2017     11   21   0.704            0
13   2017     11   22   0.920            0
14   2017     11   23   1.003            0
15   2017     11   24   2.068            0
16   2017     11   25   2.017            0
17   2017     11   26   1.809            0
18   2017     11   27   0.542            0
19   2017     11   28   1.435            0
20   2017     11   29   0.563            0
21   2017     11   30   1.054            0
22   2017     12    1   1.356            0
23   2017     12    2   0.100            0
24   2017     12    3   0.040            0
25   2017     12    4   0.045            0
26   2017     12    5   0.118            0
27   2017     12    6   0.441            0
28   2017     12    7   0.056            0
29   2017     12    8   0.896            0
..    ...    ...  ...     ...          ...         ...      ...
503  2019      3   27   0.000            0
504  2019      3   28   0.000            0
505  2019      3   29   0.000            0
506  2019      3   30   0.000            0
507  2019      3   31   0.000            0
508  2019      4    1   0.000            0
509  2019      4    2   0.000            0
510  2019      4    3   0.000            0
511  2019      4    4   0.000            0
512  2019      4    5   0.000            0
513  2019      4    6   0.000            0
514  2019      4    7   0.000            0
515  2019      4    8   0.000            0
516  2019      4    9   0.000            0
517  2019      4   10   0.000            0
518  2019      4   11   0.000            0
519  2019      4   12   0.000            0
520  2019      4   13   0.000            0
521  2019      4   14   0.000            0
522  2019      4   15   0.000            0
523  2019      4   16   0.000            0
524  2019      4   17   0.000            0
525  2019      4   18   0.000            0
526  2019      4   19   0.000            0
527  2019      4   20   0.000            0
528  2019      4   21   0.000            0
529  2019      4   22   0.000            0
530  2019      4   23   0.000            0
531  2019      4   24   0.000            0
532  2019      4   25   0.000            0

[533 rows x 7 columns]

In [53]:
alask_palmer_new['Interpolate']=0
alask_palmer_new['DC Capacity']= ""
alask_palmer_new['Location']= ""
alask_palmer_new['DC Capacity'][0]=14.4
alask_palmer_new['Location'][0]='Palmer'
alask_palmer_new.to_csv('alask_palmer_new',index=False)
alask_palmer_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity Location
0    2018      1   24   0.586            0        14.4   Palmer
1    2018      1   25   0.000            0
2    2018      1   26   0.031            0
3    2018      1   27   0.193            0
4    2018      1   28   0.280            0
5    2018      1   29  13.032            0
6    2018      1   30  14.093            0
7    2018      1   31  11.038            0
8    2018      2    1  16.624            0
9    2018      2    2  17.092            0
10   2018      2    3  18.072            0
11   2018      2    4  19.374            0
12   2018      2    5  13.569            0
13   2018      2    6   1.962            0
14   2018      2    7   2.205            0
15   2018      2    8  13.371            0
16   2018      2    9  22.025            0
17   2018      2   10   5.946            0
18   2018      2   11   0.157            0
19   2018      2   12   0.734            0
20   2018      2   13  17.631            0
21   2018      2   14   4.908            0
22   2018      2   15   1.227            0
23   2018      2   16   0.585            0
24   2018      2   17   3.065            0
25   2018      2   18   0.694            0
26   2018      2   19   1.240            0
27   2018      2   20   2.742            0
28   2018      2   21   2.503            0
29   2018      2   22   0.032            0
..    ...    ...  ...     ...          ...         ...      ...
427  2019      3   27  24.792            0
428  2019      3   28  73.080            0
429  2019      3   29  64.417            0
430  2019      3   30  74.515            0
431  2019      3   31  71.020            0
432  2019      4    1  74.638            0
433  2019      4    2  54.902            0
434  2019      4    3  83.252            0
435  2019      4    4  55.899            0
436  2019      4    5  77.077            0
437  2019      4    6  43.743            0
438  2019      4    7  48.331            0
439  2019      4    8  75.249            0
440  2019      4    9  54.840            0
441  2019      4   10  80.360            0
442  2019      4   11  14.852            0
443  2019      4   12  31.450            0
444  2019      4   13  73.462            0
445  2019      4   14  87.937            0
446  2019      4   15  82.913            0
447  2019      4   16  46.370            0
448  2019      4   17   5.679            0
449  2019      4   18  36.622            0
450  2019      4   19  16.414            0
451  2019      4   20  42.138            0
452  2019      4   21  50.317            0
453  2019      4   22   8.605            0
454  2019      4   23  43.207            0
455  2019      4   24  95.289            0
456  2019      4   25  82.872            0

[457 rows x 7 columns]

In [54]:
fishhood_palmer_new['Interpolate']=0
fishhood_palmer_new['DC Capacity']= ""
fishhood_palmer_new['Location']= ""
fishhood_palmer_new['DC Capacity'][0]=9.1
fishhood_palmer_new['Location'][0]='Palmer'
fishhood_palmer_new.to_csv('fishhood_palmer_new',index=False)
fishhood_palmer_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity Location
0    2018      4   19  45.751            0         9.1   Palmer
1    2018      4   20  40.555            0
2    2018      4   21  40.325            0
3    2018      4   22  39.560            0
4    2018      4   23  31.013            0
5    2018      4   24   6.259            0
6    2018      4   25  30.028            0
7    2018      4   26  27.479            0
8    2018      4   27  22.186            0
9    2018      4   28  19.010            0
10   2018      4   29   9.849            0
11   2018      4   30  15.098            0
12   2018      5    1  20.945            0
13   2018      5    2  37.761            0
14   2018      5    3  21.002            0
15   2018      5    4  12.646            0
16   2018      5    5  26.776            0
17   2018      5    6  30.864            0
18   2018      5    7  54.289            0
19   2018      5    8  33.698            0
20   2018      5    9  17.609            0
21   2018      5   10  40.528            0
22   2018      5   11  29.659            0
23   2018      5   12  30.395            0
24   2018      5   13  41.213            0
25   2018      5   14  26.844            0
26   2018      5   15  38.989            0
27   2018      5   16  36.772            0
28   2018      5   17  37.127            0
29   2018      5   18  28.526            0
..    ...    ...  ...     ...          ...         ...      ...
342  2019      3   27  19.774            0
343  2019      3   28  45.012            0
344  2019      3   29  37.166            0
345  2019      3   30  46.348            0
346  2019      3   31  43.411            0
347  2019      4    1  46.713            0
348  2019      4    2  37.648            0
349  2019      4    3  50.902            0
350  2019      4    4  32.361            0
351  2019      4    5  47.430            0
352  2019      4    6  29.602            0
353  2019      4    7  33.741            0
354  2019      4    8  44.002            0
355  2019      4    9  30.916            0
356  2019      4   10  48.584            0
357  2019      4   11  10.337            0
358  2019      4   12  16.547            0
359  2019      4   13  45.303            0
360  2019      4   14  45.065            0
361  2019      4   15  52.889            0
362  2019      4   16  29.481            0
363  2019      4   17   2.178            0
364  2019      4   18  24.413            0
365  2019      4   19   1.956            0
366  2019      4   20  19.076            0
367  2019      4   21  23.053            0
368  2019      4   22   3.859            0
369  2019      4   23  24.137            0
370  2019      4   24  57.880            0
371  2019      4   25  58.399            0

[372 rows x 7 columns]

In [55]:
drop_the_hours(redfox_wasilla)
drop_the_hours(countryfield_wasilla)
drop_the_hours(reliance_wasilla)

redfox_wasilla_new = seperate_date(redfox_wasilla)
countryfield_wasilla_new = seperate_date(countryfield_wasilla)
reliance_wasilla_new = seperate_date(reliance_wasilla)

In [56]:
redfox_wasilla_new['Interpolate']=0
redfox_wasilla_new['DC Capacity']= ""
redfox_wasilla_new['Location']= ""
redfox_wasilla_new['DC Capacity'][0]=3.6
redfox_wasilla_new['Location'][0]='Wasilla'
redfox_wasilla_new.to_csv('redfox_wasilla_new',index=False)
redfox_wasilla_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity Location
0    2017     10   12   3.494            0         3.6  Wasilla
1    2017     10   13   2.497            0
2    2017     10   14   3.952            0
3    2017     10   15   3.300            0
4    2017     10   16   3.585            0
5    2017     10   17   3.195            0
6    2017     10   18   3.215            0
7    2017     10   19   3.006            0
8    2017     10   20   2.975            0
9    2017     10   21   2.068            0
10   2017     10   22   0.361            0
11   2017     10   23   0.251            0
12   2017     10   24   0.611            0
13   2017     10   25   0.342            0
14   2017     10   26   0.657            0
15   2017     10   27   0.573            0
16   2017     10   28   1.807            0
17   2017     10   29   0.501            0
18   2017     10   30   0.610            0
19   2017     10   31   1.323            0
20   2017     11    1   1.599            0
21   2017     11    2   1.673            0
22   2017     11    3   1.088            0
23   2017     11    4   1.399            0
24   2017     11    5   0.004            0
25   2017     11    6   0.014            0
26   2017     11    7   0.079            0
27   2017     11    8   0.084            0
28   2017     11    9   0.005            0
29   2017     11   10   0.006            0
..    ...    ...  ...     ...          ...         ...      ...
531  2019      3   27   6.537            0
532  2019      3   28  11.984            0
533  2019      3   29   9.035            0
534  2019      3   30  12.446            0
535  2019      3   31  12.755            0
536  2019      4    1  13.176            0
537  2019      4    2  11.225            0
538  2019      4    3  14.422            0
539  2019      4    4   8.487            0
540  2019      4    5  14.046            0
541  2019      4    6   9.846            0
542  2019      4    7   9.899            0
543  2019      4    8  12.961            0
544  2019      4    9   9.025            0
545  2019      4   10  12.298            0
546  2019      4   11   3.734            0
547  2019      4   12   6.193            0
548  2019      4   13  12.034            0
549  2019      4   14  14.626            0
550  2019      4   15  15.653            0
551  2019      4   16   8.211            0
552  2019      4   17   3.237            0
553  2019      4   18   6.872            0
554  2019      4   19   5.869            0
555  2019      4   20   7.882            0
556  2019      4   21  11.283            0
557  2019      4   22   4.744            0
558  2019      4   23   7.279            0
559  2019      4   24  18.155            0
560  2019      4   25  17.844            0

[561 rows x 7 columns]

In [57]:
countryfield_wasilla_new['Interpolate']=0
countryfield_wasilla_new['DC Capacity']= ""
countryfield_wasilla_new['Location']= ""
countryfield_wasilla_new['DC Capacity'][0]=3.6
countryfield_wasilla_new['Location'][0]='Wasilla'
countryfield_wasilla_new.to_csv('countryfield_wasilla_new',index=False)
countryfield_wasilla_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity Location
0    2018      1    8   0.000            0         3.6  Wasilla
1    2018      1    9   0.302            0
2    2018      1   10   0.120            0
3    2018      1   11   0.097            0
4    2018      1   12   0.285            0
5    2018      1   13   0.085            0
6    2018      1   14   0.365            0
7    2018      1   15   0.118            0
8    2018      1   16   0.322            0
9    2018      1   17   0.144            0
10   2018      1   18   0.391            0
11   2018      1   19   0.320            0
12   2018      1   20   0.328            0
13   2018      1   21   0.233            0
14   2018      1   22   0.313            0
15   2018      1   23   0.036            0
16   2018      1   24   0.006            0
17   2018      1   25   0.000            0
18   2018      1   26   1.041            0
19   2018      1   27   1.942            0
20   2018      1   28   2.354            0
21   2018      1   29   2.461            0
22   2018      1   30   2.620            0
23   2018      1   31   2.712            0
24   2018      2    1   2.940            0
25   2018      2    2   3.023            0
26   2018      2    3   3.204            0
27   2018      2    4   3.311            0
28   2018      2    5   2.449            0
29   2018      2    6   0.742            0
..    ...    ...  ...     ...          ...         ...      ...
443  2019      3   27   8.165            0
444  2019      3   28  16.274            0
445  2019      3   29  14.416            0
446  2019      3   30  16.827            0
447  2019      3   31  16.094            0
448  2019      4    1  17.151            0
449  2019      4    2  12.894            0
450  2019      4    3  18.654            0
451  2019      4    4  12.274            0
452  2019      4    5  17.450            0
453  2019      4    6  10.539            0
454  2019      4    7  12.590            0
455  2019      4    8  16.266            0
456  2019      4    9  14.323            0
457  2019      4   10  17.439            0
458  2019      4   11   3.819            0
459  2019      4   12   6.738            0
460  2019      4   13  19.424            0
461  2019      4   14  18.400            0
462  2019      4   15  20.754            0
463  2019      4   16  10.392            0
464  2019      4   17   0.337            0
465  2019      4   18   4.524            0
466  2019      4   19   2.122            0
467  2019      4   20   4.960            0
468  2019      4   21  15.527            0
469  2019      4   22   3.499            0
470  2019      4   23   8.181            0
471  2019      4   24  20.986            0
472  2019      4   25  21.727            0

[473 rows x 7 columns]

In [58]:
reliance_wasilla_new['Interpolate']=0
reliance_wasilla_new['DC Capacity']= ""
reliance_wasilla_new['Location']= ""
reliance_wasilla_new['DC Capacity'][0]=6
reliance_wasilla_new['Location'][0]='Wasilla'
reliance_wasilla_new.to_csv('reliance_wasilla_new',index=False)
reliance_wasilla_new

/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
/miniconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

     Year  Month  Day  Energy  Interpolate DC Capacity Location
0    2018      3   29   1.443            0           6  Wasilla
1    2018      3   30   2.801            0
2    2018      3   31  11.175            0
3    2018      4    1  17.139            0
4    2018      4    2  23.384            0
5    2018      4    3  25.131            0
6    2018      4    4  28.606            0
7    2018      4    5  29.161            0
8    2018      4    6  29.161            0
9    2018      4    7  29.161            0
10   2018      4    8  29.161            0
11   2018      4    9  29.161            0
12   2018      4   10  29.161            0
13   2018      4   11  29.161            0
14   2018      4   12  29.161            0
15   2018      4   13  29.161            0
16   2018      4   14  29.161            0
17   2018      4   15  29.161            0
18   2018      4   16  29.161            0
19   2018      4   17  29.161            0
20   2018      4   18  29.161            0
21   2018      4   19  29.161            0
22   2018      4   20  29.161            0
23   2018      4   21  29.161            0
24   2018      4   22  29.161            0
25   2018      4   23  29.161            0
26   2018      4   24  29.161            0
27   2018      4   25  29.161            0
28   2018      4   26  29.161            0
29   2018      4   27  29.161            0
..    ...    ...  ...     ...          ...         ...      ...
363  2019      3   27  15.050            0
364  2019      3   28  26.531            0
365  2019      3   29  20.897            0
366  2019      3   30  27.043            0
367  2019      3   31  25.820            0
368  2019      4    1  27.908            0
369  2019      4    2  25.040            0
370  2019      4    3  29.423            0
371  2019      4    4  17.324            0
372  2019      4    5  29.004            0
373  2019      4    6  18.109            0
374  2019      4    7  21.832            0
375  2019      4    8  22.246            0
376  2019      4    9  23.797            0
377  2019      4   10  27.016            0
378  2019      4   11   7.613            0
379  2019      4   12  11.183            0
380  2019      4   13  31.770            0
381  2019      4   14  32.997            0
382  2019      4   15  34.018            0
383  2019      4   16  20.278            0
384  2019      4   17   0.002            0
385  2019      4   18   1.074            0
386  2019      4   19   1.592            0
387  2019      4   20   7.385            0
388  2019      4   21  18.519            0
389  2019      4   22   0.825            0
390  2019      4   23   3.099            0
391  2019      4   24  29.481            0
392  2019      4   25  37.351            0

[393 rows x 7 columns]

In [59]:
drop_the_hours(woodside_homer)
woodside_homer_new = seperate_date(woodside_homer)

In [ ]:
woodside_homer_new['Interpolate']=0
woodside_homer_new['DC Capacity']= ""
woodside_homer_new['Location']= ""
woodside_homer_new['DC Capacity'][0]=6
woodside_homer_new['Location'][0]='Wasilla'
woodside_homer_new.to_csv('reliance_wasilla_new',index=False)
woodside_homer_new